'use strict';
const assert = require('node:assert/strict');
const { layoutInlineRuns } = require('./pdfInlineLayout');
const measureText = text => [...text].length * 5;
const formula = { kind: 'formula', latex: '\\frac{H}{2t}', media: { width: 24, height: 32 } };
const layout = tokens => layoutInlineRuns({ tokens, maxWidth: 80, size: 10, lineHeight: 12, measureText });
const lines = layout([{ kind: 'text', text: 'Before ' }, formula, { kind: 'text', text: ' after' }]);
assert.equal(lines.length, 1, 'inline formula must share the prose line when it fits');
assert.deepEqual(lines[0].runs.map(run => run.kind), ['text', 'text', 'formula', 'text', 'text']);
assert.equal(lines[0].runs[2].token, formula, 'the original graphical formula must survive layout');
assert.equal(lines[0].height, 20, 'fraction line height must accommodate the measured formula');
const wrapped = layout([{ kind: 'text', text: 'a'.repeat(15) }, formula, { kind: 'text', text: 'end' }]);
assert.equal(wrapped.length, 2);
assert.equal(wrapped[1].runs[0].kind, 'formula');
assert(wrapped.every(line => line.width <= 80 && line.height >= 12));
const oversized = layout([{ kind: 'text', text: 'x'.repeat(65) }, { ...formula, media: {width: 900, height: 20} }]);
assert(oversized.length >= 5 && oversized.every(line => line.width <= 80));
assert.equal(oversized.at(-1).runs.at(-1).kind, 'formula');
const chinese = layout([{ kind: 'text', text: '\u6c49'.repeat(31) + '\n\u5b57' }]);
assert.equal(chinese.length, 3);
assert.equal(chinese.at(-1).runs[0].text, '\u5b57');
assert.deepEqual(layout([{kind:'text',text:''}]), []);
assert.throws(()=>layout([{...formula,media:{width:NaN,height:1}}]), /CLOUD_PAPER_RENDER_FORMULA_INVALID/);
console.log('PDF inline layout checks passed');
