'use strict';
const crypto=require('node:crypto');
const {validateRecord,validDate}=require('../../shared/personal-finance/ledger');
const failure=code=>Object.assign(new Error('CLOUD_PERSONAL_FINANCE_'+code),{code:'CLOUD_PERSONAL_FINANCE_'+code});
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const text=(v,max=512)=>{if(typeof v!=='string'||!v.trim()||v!==v.trim()||v.length>max)throw failure('INPUT_INVALID');return v;};
const stable=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(stable).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';
const hash=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:stable(v)).digest('hex');
const id=prefix=>prefix+'_'+crypto.randomUUID();
function scope(input){const a=input?.actor;if(!object(a)||typeof a.accountId!=='string'||!a.accountId.trim()||!Array.isArray(a.roles)||!a.roles.some(r=>['teacher','super_admin'].includes(r)))throw failure('ACCESS_DENIED');return [text(input.tenantId,128),text(a.accountId)];}
const ACCOUNT_KEYS=['id','label','provider','type','maskedIdentifier','currency','openingBalanceMinor','openingDate','status'];
function accountData(value,accountId){
 if(!object(value)||Object.keys(value).some(k=>!ACCOUNT_KEYS.includes(k)))throw failure('INPUT_INVALID');
 const account={id:accountId||value.id||id('finance_account'),label:value.label,provider:value.provider,type:value.type,maskedIdentifier:value.maskedIdentifier??'',currency:value.currency,openingBalanceMinor:value.openingBalanceMinor??null,openingDate:value.openingDate??null,status:value.status??'active'};
 text(account.id);text(account.label,128);text(account.provider,128);
 if(!['cash','bank','savings','debit_card','credit_card','wallet','loan','other','investment','insurance','receivable','property','precious_metal','retirement'].includes(account.type)||typeof account.maskedIdentifier!=='string'||account.maskedIdentifier.length>128||!/^[A-Z]{3}$/.test(account.currency||'')||!['active','archived'].includes(account.status))throw failure('INPUT_INVALID');
 if(account.openingBalanceMinor!==null && !(typeof account.openingBalanceMinor==='string'&&/^-?(0|[1-9]\d*)$/.test(account.openingBalanceMinor)))throw failure('INPUT_INVALID');
 if(account.openingDate!==null&&!validDate(account.openingDate)||account.openingBalanceMinor!==null&&account.openingDate===null)throw failure('INPUT_INVALID');return account;
}
function createPersonalFinanceRepository({query,transaction,parseBillFile,archiveSource}={}){
 if(typeof query!=='function'||typeof transaction!=='function'||typeof parseBillFile!=='function'||archiveSource!==undefined&&typeof archiveSource!=='function')throw failure('INPUT_INVALID');
 async function lock(q,owner,expectedRevision){
  await q('INSERT INTO business.personal_finance_owners(tenant_id,account_id) VALUES($1,$2) ON CONFLICT DO NOTHING',owner);
  const row=(await q('SELECT revision::text AS revision FROM business.personal_finance_owners WHERE tenant_id=$1 AND account_id=$2 FOR UPDATE',owner)).rows[0];
  if(!row)throw failure('UNAVAILABLE');
  if(expectedRevision!==undefined){if(!/^(0|[1-9]\d*)$/.test(String(expectedRevision)))throw failure('INPUT_INVALID');if(String(expectedRevision)!==row.revision)throw failure('REVISION_CONFLICT');}return row.revision;
 }
 async function account(q,owner,financialAccountId){const result=await q('SELECT data FROM business.personal_finance_accounts WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,text(financialAccountId)]);if(!result.rows[0])throw failure('ACCOUNT_NOT_FOUND');return result.rows[0].data;}
 async function changed(q,owner,action,data){const row=(await q('UPDATE business.personal_finance_owners SET revision=revision+1 WHERE tenant_id=$1 AND account_id=$2 RETURNING revision::text AS revision',owner)).rows[0];await q('INSERT INTO business.personal_finance_audit(id,tenant_id,account_id,revision,action,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[id('finance_audit'),...owner,row.revision,action,JSON.stringify(data)]);return row.revision;}
 function fileInput(input){text(input.filename,256);if(/[\\/\x00-\x1f]/.test(input.filename))throw failure('INPUT_INVALID');if(typeof input.base64!=='string'||input.base64.length>28*1024*1024||input.base64.length%4!==0||/[^A-Za-z0-9+/=]/.test(input.base64))throw failure('INPUT_INVALID');const buffer=Buffer.from(input.base64,'base64');if(!buffer.length||buffer.length>20*1024*1024||buffer.toString('base64')!==input.base64)throw failure('INPUT_INVALID');return buffer;}
 async function parse(input,owner,buffer,q=query){
  const selected=await account(q,owner,input.financialAccountId);if(selected.status!=='active')throw failure('ACCOUNT_ARCHIVED');
  const result=await parseBillFile({filename:input.filename,buffer,fieldMapping:input.fieldMapping});
  if(!object(result)||!Array.isArray(result.records)||!Array.isArray(result.errors)||!Array.isArray(result.warnings)||result.records.length>10000)throw failure('IMPORT_INVALID');
  const errors=[...result.errors];for(let i=0;i<result.records.length;i++)try{validateRecord(result.records[i]);if(result.records[i].currency!==selected.currency)throw failure('CURRENCY_MISMATCH');}catch(error){errors.push({row:i+1,code:error.code||'CLOUD_PERSONAL_FINANCE_INPUT_INVALID'});}
  return {provider:text(result.provider,128),templateId:result.templateId===null?null:text(result.templateId,128),records:result.records,errors,warnings:result.warnings,fileHash:hash(buffer)};
 }
 const api={
  async getLedger(input){const owner=scope(input);const result=await query(`SELECT jsonb_build_object(
   'revision',COALESCE((SELECT revision::text FROM business.personal_finance_owners WHERE tenant_id=$1 AND account_id=$2),'0'),
   'accounts',COALESCE((SELECT jsonb_agg(data ORDER BY id) FROM business.personal_finance_accounts WHERE tenant_id=$1 AND account_id=$2),'[]'::jsonb),
   'observations',COALESCE((SELECT jsonb_agg(data ORDER BY data->>'occurredAt',id) FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2),'[]'::jsonb),
   'annotations',COALESCE((SELECT jsonb_agg(data ORDER BY revision,id) FROM business.personal_finance_annotations WHERE tenant_id=$1 AND account_id=$2),'[]'::jsonb),
   'links',COALESCE((SELECT jsonb_agg(data ORDER BY id) FROM business.personal_finance_links WHERE tenant_id=$1 AND account_id=$2),'[]'::jsonb),
   'balanceSnapshots',COALESCE((SELECT jsonb_agg(data ORDER BY data->>'asOf',id) FROM business.personal_finance_balance_snapshots WHERE tenant_id=$1 AND account_id=$2),'[]'::jsonb),
   'imports',COALESCE((SELECT jsonb_agg(i.data||jsonb_build_object('observationIds',COALESCE((SELECT r.receipt->'observationIds' FROM business.personal_finance_receipts r WHERE r.tenant_id=i.tenant_id AND r.account_id=i.account_id AND r.receipt->>'importId'=i.id),'[]'::jsonb)) ORDER BY i.created_at,i.id) FROM business.personal_finance_imports i WHERE i.tenant_id=$1 AND i.account_id=$2),'[]'::jsonb),
   'legacyRecords',COALESCE((SELECT jsonb_agg(t.data) FROM (SELECT to_jsonb(r)||jsonb_build_object('legacyType','imported') AS data FROM business.personal_asset_records r WHERE tenant_id=$1 AND account_id=$2 UNION ALL SELECT to_jsonb(r)||jsonb_build_object('legacyType','manual') FROM business.personal_asset_manual_records r WHERE tenant_id=$1 AND account_id=$2 AND deleted=false) t),'[]'::jsonb)) AS ledger`,owner);if(!result.rows[0])throw failure('UNAVAILABLE');return result.rows[0].ledger;},
  async previewImport(input){const owner=scope(input),buffer=fileInput(input);return parse(input,owner,buffer);},
  async import(input){const owner=scope(input),buffer=fileInput(input),key=text(input.idempotencyKey,256);const preview=await parse(input,owner,buffer);if(preview.errors.length||!preview.records.length)throw failure('IMPORT_INVALID');
   const requestHash=hash({financialAccountId:input.financialAccountId,fileHash:preview.fileHash,records:preview.records,fieldMapping:input.fieldMapping??null});
   if(input.expectedRevision!==undefined&&!/^(0|[1-9]\d*)$/.test(String(input.expectedRevision)))throw failure('INPUT_INVALID');
   return transaction(async q=>{const currentRevision=await lock(q,owner);const previous=(await q('SELECT request_hash,receipt FROM business.personal_finance_receipts WHERE tenant_id=$1 AND account_id=$2 AND idempotency_key=$3',[...owner,key])).rows[0];
    if(previous){if(previous.request_hash!==requestHash)throw failure('IDEMPOTENCY_CONFLICT');return {...previous.receipt,replayed:true};}
    if(input.expectedRevision!==undefined&&String(input.expectedRevision)!==currentRevision)throw failure('REVISION_CONFLICT');
    const currentAccount=await account(q,owner,input.financialAccountId);if(currentAccount.status!=='active')throw failure('ACCOUNT_ARCHIVED');if(preview.records.some(r=>r.currency!==currentAccount.currency))throw failure('CURRENCY_MISMATCH');if(!archiveSource)throw failure('SOURCE_ARCHIVE_UNAVAILABLE');
    const archiveReference=await archiveSource({tenantId:owner[0],ownerAccountId:owner[1],filename:input.filename,buffer,fileHash:preview.fileHash});if(!object(archiveReference)||archiveReference.fileHash!==preview.fileHash||typeof archiveReference.id!=='string')throw failure('SOURCE_ARCHIVE_UNAVAILABLE');
    const importId=id('finance_import'),importData={id:importId,financialAccountId:input.financialAccountId,provider:preview.provider,templateId:preview.templateId,filename:input.filename,fileHash:preview.fileHash,archiveReference,recordCount:preview.records.length,createdAt:new Date().toISOString(),observationIds:[]};
    await q('INSERT INTO business.personal_finance_imports(id,tenant_id,account_id,financial_account_id,file_hash,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[importId,...owner,input.financialAccountId,preview.fileHash,JSON.stringify(importData)]);
    let insertedCount=0;const observationIds=[];
    for(let ordinal=0;ordinal<preview.records.length;ordinal++){
     const r=preview.records[ordinal],sourceIdentity=hash(r.sourceTransactionId?{provider:preview.provider,transaction:r.sourceTransactionId}:{fileHash:preview.fileHash,ordinal}),recordFingerprint=hash(r),sourceKey=hash({sourceIdentity,recordFingerprint});
     const priorVersions=(await q('SELECT id,data FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2 AND financial_account_id=$3 AND transaction_key=$4',[...owner,input.financialAccountId,sourceIdentity])).rows;
     const prior=priorVersions.find(p=>p.data.recordFingerprint===recordFingerprint);if(prior){observationIds.push(prior.id);continue;}
     if(priorVersions.some(p=>p.data.status==='completed'&&['amountMinor','currency','direction'].some(k=>p.data[k]!==r[k])))throw failure('SOURCE_TRANSACTION_CONFLICT');
     const observation={...r,id:id('finance_observation'),financialAccountId:input.financialAccountId,provider:preview.provider,importId,sourceOrdinal:ordinal+1,recordFingerprint,sourceIdentity,sourceVersionOrdinal:priorVersions.length+1};
     await q('INSERT INTO business.personal_finance_observations(id,tenant_id,account_id,financial_account_id,import_id,source_key,transaction_key,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)',[observation.id,...owner,input.financialAccountId,importId,sourceKey,sourceIdentity,JSON.stringify(observation)]);observationIds.push(observation.id);insertedCount++;
    }
    // Import memberships remain in the receipt; source observations are immutable, including their first import.
    const revision=await changed(q,owner,'import',{importId,observationIds,archiveReference});const receipt={importId,financialAccountId:input.financialAccountId,recordCount:preview.records.length,insertedCount,observationIds,fileHash:preview.fileHash,revision,createdAt:importData.createdAt,replayed:false};
    await q('INSERT INTO business.personal_finance_receipts(tenant_id,account_id,idempotency_key,request_hash,receipt) VALUES($1,$2,$3,$4,$5::jsonb)',[...owner,key,requestHash,JSON.stringify(receipt)]);return receipt;
   });},
  async createAccount(input){const owner=scope(input),data=accountData(input.account);return transaction(async q=>{await lock(q,owner,input.expectedRevision);const exists=await q('SELECT id FROM business.personal_finance_accounts WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,data.id]);if(exists.rows.length)throw failure('ACCOUNT_EXISTS');await q('INSERT INTO business.personal_finance_accounts(id,tenant_id,account_id,data) VALUES($1,$2,$3,$4::jsonb)',[data.id,...owner,JSON.stringify(data)]);return {account:data,revision:await changed(q,owner,'account_create',data)};});},
  async updateAccount(input){const owner=scope(input);if(!object(input.patch)||Object.keys(input.patch).some(k=>!ACCOUNT_KEYS.includes(k)||k==='id'))throw failure('INPUT_INVALID');return transaction(async q=>{await lock(q,owner,input.expectedRevision);const prior=await account(q,owner,input.id),data=accountData({...prior,...input.patch},input.id);if(data.currency!==prior.currency||data.type!==prior.type||data.provider!==prior.provider||data.maskedIdentifier!==prior.maskedIdentifier) {const existing=await q('SELECT id FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2 AND financial_account_id=$3 LIMIT 1',[...owner,input.id]);if(existing.rows.length)throw failure('ACCOUNT_IDENTITY_IMMUTABLE');}await q('UPDATE business.personal_finance_accounts SET data=$4::jsonb WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,input.id,JSON.stringify(data)]);return {account:data,revision:await changed(q,owner,'account_update',{before:prior,after:data})};});},
  async annotateObservation(input){
   const owner=scope(input),allowed=['category','kind','principalMinor','interestMinor','feeMinor'];text(input.observationId);
   if(!object(input.patch)||!Object.keys(input.patch).length||Object.keys(input.patch).some(k=>!allowed.includes(k)))throw failure('INPUT_INVALID');
   return transaction(async q=>{
    await lock(q,owner,input.expectedRevision);
    const source=(await q('SELECT data FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,input.observationId])).rows[0];if(!source)throw failure('OBSERVATION_NOT_FOUND');
    const previous=(await q('SELECT data FROM business.personal_finance_annotations WHERE tenant_id=$1 AND account_id=$2 AND observation_id=$3 ORDER BY revision DESC LIMIT 1',[...owner,input.observationId])).rows[0];
    const patch={...(previous?.data.patch||{}),...input.patch},effective={...source.data,...patch};validateRecord(effective);
    const financialAccount=await account(q,owner,source.data.financialAccountId);
    if(['income','refund','loan_drawdown'].includes(effective.kind)&&effective.direction!=='credit'||['expense','interest','fee'].includes(effective.kind)&&effective.direction!=='debit'||effective.kind==='debt_payment'&&effective.direction!=='debit'&&!['loan','credit_card'].includes(financialAccount.type))throw failure('INPUT_INVALID');
    const revision=await changed(q,owner,'transaction_annotation',{observationId:input.observationId,before:previous?.data.patch||{},after:patch});
    const annotation={id:id('finance_annotation'),observationId:input.observationId,patch,revision,createdAt:new Date().toISOString()};
    await q('INSERT INTO business.personal_finance_annotations(id,tenant_id,account_id,observation_id,revision,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[annotation.id,...owner,input.observationId,revision,JSON.stringify(annotation)]);
    return {annotation,revision};
   });
  },
  async createLink(input){const owner=scope(input),l=input.link;if(!object(l)||Object.keys(l).some(k=>!['type','observationIds','note'].includes(k))||!['duplicate','transfer','refund','distinct'].includes(l.type)||!Array.isArray(l.observationIds)||l.observationIds.length!==2||l.observationIds[0]===l.observationIds[1]||l.observationIds.some(i=>typeof i!=='string')||l.note!==undefined&&typeof l.note!=='string')throw failure('INPUT_INVALID');return transaction(async q=>{await lock(q,owner,input.expectedRevision);const sources=(await q('SELECT id,data FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2 AND id=ANY($3::text[])',[...owner,l.observationIds])).rows;if(sources.length!==2)throw failure('OBSERVATION_NOT_FOUND');const annotationRows=(await q('SELECT DISTINCT ON(observation_id) observation_id,data FROM business.personal_finance_annotations WHERE tenant_id=$1 AND account_id=$2 AND observation_id=ANY($3::text[]) ORDER BY observation_id,revision DESC',[...owner,l.observationIds])).rows;const effective=sources.map(s=>({...s.data,...annotationRows.find(r=>r.observation_id===s.id)?.data.patch}));const [a,b]=effective;if(a.currency!==b.currency||l.type==='duplicate'&&(a.amountMinor!==b.amountMinor||a.direction!==b.direction)||l.type==='transfer'&&(a.amountMinor!==b.amountMinor||a.direction===b.direction)||l.type==='refund'&&!effective.some(s=>s.kind==='refund'))throw failure('LINK_INCOMPATIBLE');
    const prior=await q("SELECT id FROM business.personal_finance_links WHERE tenant_id=$1 AND account_id=$2 AND status='active' AND LEAST(observation_a,observation_b)=LEAST($3,$4) AND GREATEST(observation_a,observation_b)=GREATEST($3,$4)",[...owner,...l.observationIds]);if(prior.rows.length)throw failure('LINK_EXISTS');
    const link={...l,id:id('finance_link'),note:l.note||'',status:'active',source:'manual',createdAt:new Date().toISOString()};await q('INSERT INTO business.personal_finance_links(id,tenant_id,account_id,observation_a,observation_b,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[link.id,...owner,...l.observationIds,JSON.stringify(link)]);return {link,revision:await changed(q,owner,'link_create',link)};});},
  async deleteLink(input){const owner=scope(input);text(input.id);return transaction(async q=>{await lock(q,owner,input.expectedRevision);const row=(await q('SELECT data FROM business.personal_finance_links WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,input.id])).rows[0];if(!row)throw failure('LINK_NOT_FOUND');const link={...row.data,status:'deleted',deletedAt:new Date().toISOString()};await q("UPDATE business.personal_finance_links SET status='deleted',data=$4::jsonb WHERE tenant_id=$1 AND account_id=$2 AND id=$3",[...owner,input.id,JSON.stringify(link)]);return {link,revision:await changed(q,owner,'link_delete',{before:row.data,after:link})};});},
  async createBalanceSnapshot(input){const owner=scope(input),s=input.snapshot;if(!object(s)||Object.keys(s).some(k=>!['financialAccountId','asOf','balanceMinor','currency','source','sourceObservationId','note'].includes(k))||typeof s.balanceMinor!=='string'||! /^-?(0|[1-9]\d*)$/.test(s.balanceMinor)||typeof s.asOf!=='string'||!/T.*(?:Z|[+-]\d{2}:\d{2})$/.test(s.asOf)||Number.isNaN(Date.parse(s.asOf))||!['manual','statement'].includes(s.source)||s.source==='statement'&&!s.sourceObservationId||!/^[A-Z]{3}$/.test(s.currency||''))throw failure('INPUT_INVALID');return transaction(async q=>{await lock(q,owner,input.expectedRevision);const selected=await account(q,owner,s.financialAccountId);if(selected.currency!==s.currency)throw failure('CURRENCY_MISMATCH');if(s.sourceObservationId){const source=(await q('SELECT data FROM business.personal_finance_observations WHERE tenant_id=$1 AND account_id=$2 AND id=$3',[...owner,s.sourceObservationId])).rows[0];if(!source||source.data.financialAccountId!==s.financialAccountId)throw failure('OBSERVATION_NOT_FOUND');if(s.source==='statement'&&(source.data.balanceMinor!==s.balanceMinor||Date.parse(source.data.occurredAt)!==Date.parse(s.asOf)))throw failure('INPUT_INVALID');}const snapshot={...s,id:id('finance_snapshot'),createdAt:new Date().toISOString()};await q('INSERT INTO business.personal_finance_balance_snapshots(id,tenant_id,account_id,financial_account_id,data) VALUES($1,$2,$3,$4,$5::jsonb)',[snapshot.id,...owner,s.financialAccountId,JSON.stringify(snapshot)]);return {snapshot,revision:await changed(q,owner,'balance_snapshot',snapshot)};});},
 };
 return Object.freeze(api);
}
module.exports={createPersonalFinanceRepository};
