const assert = require('assert');
const { createAuthRateLimiter } = require('./authRateLimiter');
let clock = 0;
const limiter = createAuthRateLimiter({ maxKeys: 20, now: () => clock });
for (let i = 0; i < 100; i += 1) limiter.check({ ip: `ip-${i}`, identifier: `code-${i}` });
assert(limiter.size() <= 20);
clock = 61000;
limiter.purge();
assert.strictEqual(limiter.size(), 0);
console.log('gateway auth rate limiter checks passed');
