'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const crypto = require('node:crypto');
const source = fs.readFileSync(require.resolve('./localQuestionIntakePreview.ts'), 'utf8');
const cache = new Map();
const exportsObject = {};
new Function('require', 'exports', ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText)(() => ({ getQuestionAssetDataUrl: async key => cache.get(key), storeQuestionAsset: async () => '' }), exportsObject);
(async () => {
  const oldBytes = Buffer.from('old source image'), newBytes = Buffer.from('new uploaded image');
  const oldHash = crypto.createHash('sha256').update(oldBytes).digest('hex'), newHash = crypto.createHash('sha256').update(newBytes).digest('hex');
  cache.set(oldHash, 'data:image/png;base64,' + oldBytes.toString('base64'));
  cache.set(newHash, 'data:image/png;base64,' + newBytes.toString('base64'));
  const parsed = { candidates: [{ candidate: { assets: [{ assetIndex: 0, fileName: 'source.png', contentHash: oldHash }] } }], mediaBytes: [[oldBytes]] };
  const doc = keys => ({ rich_content: { type: 'question-document', sections: { stem: { type: 'doc', content: keys.map(key => ({ type: 'image', attrs: { assetKey: key } })) } } } });
  const edited = await exportsObject.collectEditedIntakeMedia(parsed, [doc([newHash, newHash])]);
  assert.equal(edited.candidates[0].candidate.assets.length, 1, 'deduplicate references');
  assert.equal(edited.candidates[0].candidate.assets[0].contentHash, newHash, 'new upload replaces deleted source media');
  assert.deepEqual(Buffer.from(edited.mediaBytes[0][0]), newBytes);
  assert.equal(edited.candidates[0].mediaManifest[0].sha256, newHash);
  assert.equal(parsed.candidates[0].candidate.assets[0].contentHash, oldHash, 'original parsed result stays unchanged');
  const deleted = await exportsObject.collectEditedIntakeMedia(parsed, [doc([])]);
  assert.equal(deleted.mediaBytes[0].length, 0, 'deleted image is never allocated');
  cache.set(`image-${newHash}`, 'data:image/png;base64,' + newBytes.toString('base64'));
  const inserted = await exportsObject.collectEditedIntakeMedia(parsed, [{ ...doc([`image-${newHash}`]), type: '解答题', stem: '新题干', content: '新题干', analysis: `<img src="question-asset://image-${newHash}">` }]);
  assert.equal(inserted.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.assetKey, newHash, 'actual editor image-key is canonicalized');
  assert.equal(inserted.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.src, `question-asset://${newHash}`);
  assert.equal(inserted.candidates[0].candidate.content, '新题干');
  assert.equal(inserted.candidates[0].candidate.analysis, `<img src="question-asset://${newHash}">`, 'legacy projections use the same canonical references');
  const formulaParsed = { ...parsed, candidates: [{ candidate: { assets: [{ assetIndex: 0, assetType: 'formula_preview', fileName: 'preview.png', contentHash: oldHash }] } }] };
  const formula = await exportsObject.collectEditedIntakeMedia(formulaParsed, [{rich_content:{type:'question-document',sections:{stem:{type:'doc',content:[{type:'formula',attrs:{canonicalLatex:'x',previewRef:'word/media/preview.png'}}]}}}}]);
  assert.equal(formula.candidates[0].candidate.assets[0].assetType, 'formula_preview');
  assert.equal(formula.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.previewRef, `question-asset://${oldHash}`, 'preview aliases resolve to the archived media digest');
  const convertedParsed = { ...parsed, candidates: [{ candidate: { assets: [{ assetIndex: 0, assetType: 'formula_preview', fileName: 'preview.png', mimeType: 'image/png', contentHash: oldHash }] } }] };
  const converted = await exportsObject.collectEditedIntakeMedia(convertedParsed, [{ rich_content: { type: 'question-document', sections: { stem: { type: 'doc', content: [{ type: 'formula', attrs: { canonicalLatex: 'x', previewRef: 'word/media/preview.wmf' } }] } } } }]);
  assert.equal(converted.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.previewRef, `question-asset://${oldHash}`, 'Word WMF/EMF conversion preserves formula preview provenance');
  const noPreview = { candidates: [{ candidate: { assets: [] } }], mediaBytes: [[]] };
  const nativeFormula = { rich_content: { type: 'question-document', sections: { stem: { type: 'doc', content: [{ type: 'formula', attrs: { canonicalLatex: 'x', conversionStatus: 'complete', sourceRef: 'word/embeddings/oleObject.bin', previewRef: 'word/media/formula.wmf' } }] } } } };
  const nativeResult = await exportsObject.collectEditedIntakeMedia(noPreview, [nativeFormula]);
  assert.equal(nativeResult.mediaBytes[0].length, 0);
  assert.equal(nativeResult.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.previewRef, undefined, 'successful native conversion needs no discarded bitmap preview');
  assert.equal(nativeResult.candidates[0].candidate.rich_content.sections.stem.content[0].attrs.sourceRef, 'word/embeddings/oleObject.bin');
  await assert.rejects(exportsObject.collectEditedIntakeMedia(noPreview, [{ rich_content: { type: 'question-document', sections: { stem: { type: 'doc', content: [{ type: 'formula', attrs: { canonicalLatex: '', conversionStatus: 'preview_only', previewRef: 'word/media/formula.wmf' } }] } } } }]), /PREVIEW_UNAVAILABLE/, 'unconverted original-only formulas still require their visual media');
  cache.set(oldHash, 'data:image/bmp;base64,' + oldBytes.toString('base64'));
  const bmp = await exportsObject.collectEditedIntakeMedia(parsed, [doc([oldHash])]);
  assert.equal(bmp.candidates[0].candidate.assets[0].mimeType, 'image/bmp', 'existing Word BMP image is retained');
  cache.set(newHash, 'data:image/png;base64,' + oldBytes.toString('base64'));
  await assert.rejects(exportsObject.collectEditedIntakeMedia(parsed, [doc([newHash])]), /HASH_MISMATCH/);
  console.log('edited intake media: upload, deletion, deduplication, digest integrity and immutable source passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
