const pageInventory = [
  {
    route: 'pages/login/index',
    title: '\u4e91\u7aef\u8d26\u53f7\u767b\u5f55',
    registered: true,
    roleViews: ['guest'],
    surface: 'auth',
    visualStatus: 'optimized',
    verificationStates: ['wechat-phone-proof', 'cloud-login', 'visitor-session', 'formal-session', 'identity-rejected', 'loading'],
    realFeatureBasis: ['Button(openType=getPhoneNumber)', 'POST /api/miniapp/cloud-login', 'cloud miniapp account session', 'auth_token storage for authenticated cloud users only'],
    screenshotRequired: true,
    files: ['src/pages/login/index.tsx', 'src/pages/login/index.scss'],
  },
  {
    route: 'pages/login/privacy',
    title: '隐私政策',
    registered: true,
    roleViews: ['guest'],
    surface: 'auth',
    visualStatus: 'optimized',
    verificationStates: ['privacy-content'],
    realFeatureBasis: ['app.config.ts registered page', 'static privacy policy content'],
    screenshotRequired: true,
    files: ['src/pages/login/privacy.tsx', 'src/pages/login/privacy.scss'],
  },
  {
    route: 'pages/desktop-online-registration/index',
    title: '\u5728\u7ebf\u7535\u8111\u767b\u8bb0',
    registered: true,
    roleViews: ['guest'],
    surface: 'cloud-device-pairing',
    visualStatus: 'optimized',
    verificationStates: ['scan-code', 'wechat-phone-verification', 'cloud-confirmed', 'network-error'],
    realFeatureBasis: ['Taro.scanCode(qrCode)', 'Button(openType=getPhoneNumber)', 'POST /api/desktop/pairing/confirm', 'cloud silent device registration'],
    screenshotRequired: true,
    files: ['src/pages/desktop-online-registration/index.tsx', 'src/pages/desktop-online-registration/index.scss'],
  },
  {
    route: 'pages/index/index',
    title: '首页工作台',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student', 'visitor'],
    surface: 'role-dashboard',
    visualStatus: 'optimized',
    verificationStates: ['admin-dashboard', 'student-dashboard', 'empty-modules', 'visitor-account'],
    realFeatureBasis: ['pullFromCloudBusinessProjection', 'createCloudBusinessProjectionRuntime', 'getMiniappRolePolicy', 'setBusinessCacheIdentity', 'cloud-scoped schedules/students/courses cache'],
    screenshotRequired: true,
    files: ['src/pages/index/index.tsx', 'src/pages/index/index.scss'],
  },
  {
    route: 'pages/schedule/index',
    title: '课程表',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student', 'visitor'],
    surface: 'readonly-schedule',
    visualStatus: 'optimized',
    verificationStates: ['week-view', 'day-view', 'empty-day', 'visitor-empty'],
    realFeatureBasis: ['scheduleApi.getAll', 'cached schedules', 'cached courses', 'pages/schedule/detail/index'],
    screenshotRequired: true,
    files: ['src/pages/schedule/index.tsx', 'src/pages/schedule/index.scss'],
  },
  {
    route: 'pages/schedule/detail/index',
    title: '排课详情',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student'],
    surface: 'readonly-detail',
    visualStatus: 'optimized',
    verificationStates: ['course-detail', 'missing-record'],
    realFeatureBasis: ['getLocalItem(schedules)', 'local courses', 'local students', 'pages/student-detail/index'],
    screenshotRequired: true,
    files: ['src/pages/schedule/detail/index.tsx', 'src/pages/schedule/detail/detail.scss'],
  },
  {
    route: 'pages/schedule/edit/index',
    title: '排课编辑限制',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student'],
    surface: 'limited-write-explainer',
    visualStatus: 'optimized',
    verificationStates: ['miniapp-readonly-boundary'],
    realFeatureBasis: ['微信小程序只读/有限写入约束', 'desktop-only schedule editing policy'],
    screenshotRequired: true,
    files: ['src/pages/schedule/edit/index.tsx', 'src/pages/schedule/edit/edit.scss'],
  },
  {
    route: 'pages/students/index',
    title: '学生列表',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'admin-list',
    visualStatus: 'optimized',
    verificationStates: ['search', 'list', 'empty'],
    realFeatureBasis: ['studentApi.getAll', 'local students', 'pages/student-detail/index'],
    screenshotRequired: true,
    files: ['src/pages/students/index.tsx', 'src/pages/students/index.scss'],
  },
  {
    route: 'pages/student-detail/index',
    title: '学生详情',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student'],
    surface: 'role-scoped-detail',
    visualStatus: 'optimized',
    verificationStates: ['info-tab', 'payments-tab', 'grades-tab', 'missing-student'],
    realFeatureBasis: ['local students', 'local payments', 'local grades'],
    screenshotRequired: true,
    files: ['src/pages/student-detail/index.tsx', 'src/pages/student-detail/index.scss'],
  },
  {
    route: 'pages/courses/index',
    title: '课程管理',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'admin-filtered-list',
    visualStatus: 'optimized',
    verificationStates: ['active-courses', 'inactive-courses', 'empty'],
    realFeatureBasis: ['courseApi.getAll', 'local courses', 'CourseType'],
    screenshotRequired: true,
    files: ['src/pages/courses/index.tsx', 'src/pages/courses/index.scss'],
  },
  {
    route: 'pages/teachers/index',
    title: '教师列表',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'admin-list',
    visualStatus: 'optimized',
    verificationStates: ['list', 'empty'],
    realFeatureBasis: ['teacherApi.getAll', 'local teachers'],
    screenshotRequired: true,
    files: ['src/pages/teachers/index.tsx', 'src/pages/teachers/index.scss'],
  },
  {
    route: 'pages/payments/index',
    title: '缴费记录',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'admin-finance-list',
    visualStatus: 'optimized',
    verificationStates: ['summary', 'student-filter', 'empty'],
    realFeatureBasis: ['paymentApi.getAll', 'local payments', 'local students'],
    screenshotRequired: true,
    files: ['src/pages/payments/index.tsx', 'src/pages/payments/index.scss'],
  },
  {
    route: 'pages/stats/index',
    title: '数据统计',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'admin-analytics',
    visualStatus: 'optimized',
    verificationStates: ['revenue-summary', 'course-type-bars', 'empty'],
    realFeatureBasis: ['local schedules', 'local courses', 'ScheduleStatus.COMPLETED'],
    screenshotRequired: true,
    files: ['src/pages/stats/index.tsx', 'src/pages/stats/index.scss'],
  },
  {
    route: 'pages/question-bank/index',
    title: '题库组卷与导出',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student', 'visitor'],
    surface: 'limited-write-task',
    visualStatus: 'optimized',
    verificationStates: ['preview-loading', 'preview-empty', 'preview-offline', 'preview-forbidden', 'paper-form', 'persistent-task-list', 'task-actions', 'task-result', 'visitor-preview'],
    realFeatureBasis: ['miniappCloudBusinessApi.listQuestionPreviews', 'local ordered question-paper draft', 'miniappCloudBusinessApi.createPaperExportTask(paper-export-word)', 'miniappCloudBusinessApi.createPaperExportTask(paper-export-pdf)', 'miniappCloudBusinessApi.cancelPaperExportTask', 'miniappCloudBusinessApi.readPaperExportTask', 'miniappCloudBusinessApi.requestPaperExportDelivery', 'miniappCloudBusinessApi.downloadPaperExportDelivery'],
    screenshotRequired: true,
    files: ['src/pages/question-bank/index.tsx', 'src/pages/question-bank/index.scss'],
  },
  {
    route: 'pages/assets/index',
    title: '财务资产',
    registered: true,
    roleViews: ['super_admin', 'teacher'],
    surface: 'limited-write-finance',
    visualStatus: 'optimized',
    verificationStates: ['import-task', 'overview', 'category-stats', 'empty'],
    realFeatureBasis: ['createMiniappTask(asset-import)', 'local assetRecords', 'local assetCategories'],
    screenshotRequired: true,
    files: ['src/pages/assets/index.tsx', 'src/pages/assets/index.scss'],
  },
  {
    route: 'pages/settings/index',
    title: '我的与同步设置',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student', 'visitor'],
    surface: 'role-settings-sync',
    visualStatus: 'optimized',
    verificationStates: ['online', 'offline', 'pending-sync', 'logout', 'visitor-account-application', 'role-application-review'],
    realFeatureBasis: ['getApiBaseUrl', 'setApiBaseUrl', 'getPendingChanges', 'triggerSync', 'pullFromCloud', 'pages/account-application/index'],
    screenshotRequired: true,
    files: ['src/pages/settings/index.tsx', 'src/pages/settings/index.scss'],
  },
  {
    route: 'pages/forbidden/index',
    title: '无权限状态',
    registered: true,
    roleViews: ['super_admin', 'teacher', 'student', 'visitor'],
    surface: 'permission-state',
    visualStatus: 'optimized',
    verificationStates: ['blocked-module'],
    realFeatureBasis: ['hasModulePermission', 'pages/index/index handleModuleClick forbidden redirect', 'app.config.ts registered page'],
    screenshotRequired: true,
    files: ['src/pages/forbidden/index.tsx', 'src/pages/forbidden/index.scss'],
  },
  {
    route: 'pages/account-application/index',
    title: '角色申请',
    registered: true,
    roleViews: ['visitor'],
    surface: 'visitor',
    visualStatus: 'optimized',
    verificationStates: ['loading', 'not-submitted', 'invalid', 'submitting', 'submitted', 'rejected', 'approved', 'offline', 'network-error'],
    realFeatureBasis: ['miniappCloudBusinessApi.readRoleApplication', 'miniappCloudBusinessApi.submitRoleApplication', 'cloud visitor role application'],
    screenshotRequired: true,
    files: ['src/pages/account-application/index.tsx', 'src/pages/account-application/index.scss'],
  },
];

const { runtimeScenarios } = require('./miniappUiRuntimeScenarios');
for (const entry of pageInventory) {
  entry.runtimeScenarioIds = runtimeScenarios.filter(scenario => scenario.route === entry.route).map(scenario => scenario.id);
}

module.exports = { pageInventory: Object.freeze(pageInventory.map(entry => Object.freeze(entry))) };
