const pageInventory = [
  {
    route: 'pages/login/index',
    title: '微信手机号验证与待审核',
    registered: true,
    roleViews: ['guest'],
    surface: 'auth',
    visualStatus: 'optimized',
    verificationStates: ['wechat-login', 'verified-phone-binding', 'pending-review', 'loading'],
    realFeatureBasis: ['api.post(/api/auth/wechat-login)', 'Button(open-type=getPhoneNumber)', 'PHONE_VERIFICATION_REQUIRED', 'PENDING_REVIEW', 'auth_token storage for approved users only'],
    screenshotRequired: true,
    files: ['src/pages/login/index.tsx', 'src/pages/login/index.scss'],
  },
  {
    route: 'pages/index/index',
    title: '首页工作台',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'role-dashboard',
    visualStatus: 'optimized',
    verificationStates: ['admin-dashboard', 'student-dashboard', 'empty-modules'],
    realFeatureBasis: ['readCloudSnapshot(full)', 'api.get(/api/modules)', 'getMiniappRolePolicy', 'local schedules/students/courses'],
    screenshotRequired: true,
    files: ['src/pages/index/index.tsx', 'src/pages/index/index.scss'],
  },
  {
    route: 'pages/schedule/index',
    title: '课程表',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'readonly-schedule',
    visualStatus: 'optimized',
    verificationStates: ['week-view', 'day-view', 'empty-day'],
    realFeatureBasis: ['scheduleApi.getAll', 'cached schedules', 'cached courses', 'pages/schedule/detail/index'],
    screenshotRequired: true,
    files: ['src/pages/schedule/index.tsx', 'src/pages/schedule/index.scss'],
  },
  {
    route: 'pages/schedule/detail/index',
    title: '排课详情',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'readonly-detail',
    visualStatus: 'optimized',
    verificationStates: ['course-detail', 'missing-record'],
    realFeatureBasis: ['getLocalItem(schedules)', 'local courses', 'local students', 'pages/student-detail/index'],
    screenshotRequired: true,
    files: ['src/pages/schedule/detail/index.tsx', 'src/pages/schedule/detail/detail.scss'],
  },
  {
    route: 'pages/schedule/edit/index',
    title: '排课编辑限制',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'limited-write-explainer',
    visualStatus: 'optimized',
    verificationStates: ['miniapp-readonly-boundary'],
    realFeatureBasis: ['微信小程序只读/有限写入约束', 'desktop-only schedule editing policy'],
    screenshotRequired: true,
    files: ['src/pages/schedule/edit/index.tsx', 'src/pages/schedule/edit/edit.scss'],
  },
  {
    route: 'pages/students/index',
    title: '学生列表',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-list',
    visualStatus: 'optimized',
    verificationStates: ['search', 'list', 'empty'],
    realFeatureBasis: ['studentApi.getAll', 'local students', 'pages/student-detail/index'],
    screenshotRequired: true,
    files: ['src/pages/students/index.tsx', 'src/pages/students/index.scss'],
  },
  {
    route: 'pages/student-detail/index',
    title: '学生详情',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'role-scoped-detail',
    visualStatus: 'optimized',
    verificationStates: ['info-tab', 'payments-tab', 'grades-tab', 'missing-student'],
    realFeatureBasis: ['local students', 'local payments', 'local grades'],
    screenshotRequired: true,
    files: ['src/pages/student-detail/index.tsx', 'src/pages/student-detail/index.scss'],
  },
  {
    route: 'pages/courses/index',
    title: '课程管理',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-filtered-list',
    visualStatus: 'optimized',
    verificationStates: ['active-courses', 'inactive-courses', 'empty'],
    realFeatureBasis: ['courseApi.getAll', 'local courses', 'CourseType'],
    screenshotRequired: true,
    files: ['src/pages/courses/index.tsx', 'src/pages/courses/index.scss'],
  },
  {
    route: 'pages/teachers/index',
    title: '教师列表',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-list',
    visualStatus: 'optimized',
    verificationStates: ['list', 'empty'],
    realFeatureBasis: ['teacherApi.getAll', 'local teachers'],
    screenshotRequired: true,
    files: ['src/pages/teachers/index.tsx', 'src/pages/teachers/index.scss'],
  },
  {
    route: 'pages/payments/index',
    title: '缴费记录',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-finance-list',
    visualStatus: 'optimized',
    verificationStates: ['summary', 'student-filter', 'empty'],
    realFeatureBasis: ['paymentApi.getAll', 'local payments', 'local students'],
    screenshotRequired: true,
    files: ['src/pages/payments/index.tsx', 'src/pages/payments/index.scss'],
  },
  {
    route: 'pages/stats/index',
    title: '数据统计',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-analytics',
    visualStatus: 'optimized',
    verificationStates: ['revenue-summary', 'course-type-bars', 'empty'],
    realFeatureBasis: ['local schedules', 'local courses', 'ScheduleStatus.COMPLETED'],
    screenshotRequired: true,
    files: ['src/pages/stats/index.tsx', 'src/pages/stats/index.scss'],
  },
  {
    route: 'pages/question-bank/index',
    title: '题库组卷与导出',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'limited-write-task',
    visualStatus: 'optimized',
    verificationStates: ['paper-form', 'task-actions', 'task-result'],
    realFeatureBasis: ['createMiniappTask(question-paper)', 'createMiniappTask(paper-export-word)', 'createMiniappTask(paper-export-pdf)', 'getMiniappTaskResult'],
    screenshotRequired: true,
    files: ['src/pages/question-bank/index.tsx', 'src/pages/question-bank/index.scss'],
  },
  {
    route: 'pages/assets/index',
    title: '财务资产',
    registered: true,
    roleViews: ['admin'],
    surface: 'limited-write-finance',
    visualStatus: 'optimized',
    verificationStates: ['import-task', 'overview', 'category-stats', 'empty'],
    realFeatureBasis: ['createMiniappTask(asset-import)', 'local assetRecords', 'local assetCategories'],
    screenshotRequired: true,
    files: ['src/pages/assets/index.tsx', 'src/pages/assets/index.scss'],
  },
  {
    route: 'pages/settings/index',
    title: '我的与同步设置',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'role-settings-sync',
    visualStatus: 'optimized',
    verificationStates: ['online', 'offline', 'pending-sync', 'logout'],
    realFeatureBasis: ['getApiBaseUrl', 'setApiBaseUrl', 'getPendingChanges', 'triggerSync', 'pullFromCloud'],
    screenshotRequired: true,
    files: ['src/pages/settings/index.tsx', 'src/pages/settings/index.scss'],
  },
  {
    route: 'pages/admin/users/index',
    title: '管理员用户权限',
    registered: true,
    roleViews: ['admin'],
    surface: 'admin-permission-workbench',
    visualStatus: 'optimized',
    verificationStates: ['user-list', 'role-review', 'pairing-review'],
    realFeatureBasis: ['adminApi.getUsers', 'adminApi.reviewUser', 'adminApi.getPendingPairings', 'adminApi.reviewPairingCode'],
    screenshotRequired: true,
    files: ['src/pages/admin/users/index.tsx', 'src/pages/admin/users/index.scss'],
  },
  {
    route: 'pages/forbidden/index',
    title: '无权限状态',
    registered: true,
    roleViews: ['admin', 'student'],
    surface: 'permission-state',
    visualStatus: 'optimized',
    verificationStates: ['blocked-module'],
    realFeatureBasis: ['hasModulePermission', 'pages/index/index handleModuleClick forbidden redirect', 'app.config.ts registered page'],
    screenshotRequired: true,
    files: ['src/pages/forbidden/index.tsx', 'src/pages/forbidden/index.scss'],
  },
];

module.exports = { pageInventory };
