'use strict';
const assert = require('node:assert/strict');
let buildFinanceView;
try { ({buildFinanceView}=require('./ledger')); } catch (error) { if(error.code!=='MODULE_NOT_FOUND') throw error; }
assert.equal(typeof buildFinanceView,'function','finance engine must exist');
const account=(id,type='bank',extra={})=>({id,label:id,provider:id,type,maskedIdentifier:id,currency:'CNY',openingBalanceMinor:null,openingDate:null,status:'active',...extra});
const observation=(id,financialAccountId,extra={})=>({id,financialAccountId,provider:financialAccountId,sourceTransactionId:id,occurredAt:'2026-10-08T10:00:00+08:00',date:'2026-10-08',amountMinor:'100',currency:'CNY',direction:'debit',kind:'expense',description:'Books',counterparty:'Shop',category:'Books',paymentChannel:'',paymentAccountHint:'',balanceMinor:null,relatedReference:'',status:'completed',principalMinor:null,interestMinor:null,feeMinor:null,rawFields:{},...extra});
const ledger=(accounts,observations,extra={})=>({accounts,observations,links:[],balanceSnapshots:[],imports:[],legacyRecords:[],revision:0,...extra});
let view=buildFinanceView(ledger([account('bank')],[observation('a','bank'),observation('b','bank')]));
assert.equal(view.transactions.length,2,'same date and amount are independent');
assert.equal(view.currencyTotals.CNY.consumptionMinor,'200');
assert.equal(view.accountStats.bank.balanceMinor,null,'flow difference is not balance');
view=buildFinanceView(ledger([account('bank','bank',{maskedIdentifier:'1234',openingBalanceMinor:'1000',openingDate:'2026-10-01'}),account('ali','wallet')],[observation('b','bank',{relatedReference:'ref1'}),observation('w','ali',{relatedReference:'ref1',paymentAccountHint:'1234',paymentChannel:'alipay'})]));
assert.equal(view.transactions.length,1,'one-to-one reference and funding evidence link sources');
assert.equal(view.currencyTotals.CNY.consumptionMinor,'100');
assert.equal(view.accountStats.bank.balanceMinor,'900');
assert.equal(view.accountStats.ali.cashOutMinor,'0','card financed wallet does not invent wallet debit');
assert.equal(view.accountStats.ali.consumptionMinor,'100','wallet channel retains consumption attribution without creating wallet cash flow');
assert.equal(view.fundingTotals.bank.CNY,'100');
view=buildFinanceView(ledger([account('bank'),account('ali','wallet')],[observation('b','bank',{relatedReference:'r'}),observation('c','bank',{relatedReference:'r'}),observation('w','ali',{relatedReference:'r',paymentAccountHint:'bank'})]));
assert.equal(view.transactions.length,3,'ambiguous candidates never silently merge');
assert.ok(view.unresolvedAssociations.some(x=>x.reason==='ambiguous_reference'));
view=buildFinanceView(ledger([account('bank'),account('card','credit_card'),account('usd','bank',{currency:'USD'})],[observation('buy','card',{amountMinor:'500'}),observation('repay','bank',{kind:'debt_payment',amountMinor:'530',principalMinor:'500',interestMinor:'20',feeMinor:'10'}),observation('loan','bank',{kind:'loan_drawdown',direction:'credit',amountMinor:'10000'}),observation('transfer','bank',{kind:'transfer',amountMinor:'700'}),observation('refund','card',{kind:'refund',direction:'credit',amountMinor:'100',relatedReference:'buy'}),observation('us','usd',{currency:'USD',amountMinor:'9007199254740993'})]));
assert.equal(view.currencyTotals.CNY.consumptionMinor,'430');
assert.equal(view.currencyTotals.CNY.incomeMinor,'0');
assert.equal(view.currencyTotals.USD.consumptionMinor,'9007199254740993');
assert.equal(view.currencyTotals.CNY.cashOutMinor,'1230','credit consumption is not current cash out');
assert.equal(view.currencyTotals.CNY.cashInMinor,'10000');
assert.equal(view.transactions.find(x=>x.observationIds.includes('refund')).relatedTransactionId,'buy');
view=buildFinanceView(ledger([account('bank')],[observation('pending','bank',{status:'pending'}),observation('unknown','bank',{kind:'debt_payment'})]));
assert.equal(view.currencyTotals.CNY.consumptionMinor,'0');
assert.ok(view.unresolvedAssociations.some(x=>x.reason==='unsplit_debt_payment'));
view=buildFinanceView(ledger([account('bank')],[observation('before','bank',{date:'2026-10-01',occurredAt:'2026-10-01T10:00:00Z'}),observation('after','bank')],{balanceSnapshots:[{id:'snap',financialAccountId:'bank',asOf:'2026-10-02T00:00:00Z',balanceMinor:'1000',currency:'CNY',source:'statement'}]}),{accountIds:['bank'],startDate:'2026-10-08',endDate:'2026-10-08'});
assert.equal(view.accountStats.bank.balanceMinor,'900');
assert.equal(view.accountStats.bank.balanceAnchor.id,'snap');
assert.equal(view.comparison.previous.currencyTotals.CNY.consumptionMinor,'0');
assert.equal(view.categoryTotals.CNY.Books,'100');
const transferSources=[observation('out','bank'),observation('in','cash',{direction:'credit',kind:'income'})];
view=buildFinanceView(ledger([account('bank'),account('cash','cash')],transferSources,{links:[{id:'transfer-link',type:'transfer',status:'active',observationIds:['out','in']}]}));
assert.equal(view.currencyTotals.CNY.consumptionMinor,'0','manual transfer evidence reclassifies both legs');
assert.equal(view.currencyTotals.CNY.incomeMinor,'0');
assert.equal(view.currencyTotals.CNY.netCashFlowMinor,'0');
view=buildFinanceView(ledger([account('bank'),account('ali','wallet')],[observation('b','bank',{relatedReference:'r'}),observation('w','ali',{relatedReference:'r',paymentAccountHint:'bank'})],{links:[{id:'unlinked',type:'duplicate',status:'deleted',observationIds:['b','w']}]}));
assert.equal(view.transactions.length,2,'unlink persists manual decision instead of silently relinking');
view=buildFinanceView(ledger([account('property','property',{openingBalanceMinor:'50000000',openingDate:'2026-01-01'})],[observation('maintenance','property',{amountMinor:'5000'})]));
assert.equal(view.accountStats.property.balanceMinor,'50000000','non-cash asset calibration never projects market value from expenses');
assert.equal(view.accountStats.property.balanceStatus,'calibrated');
view=buildFinanceView(ledger([account('bank','bank',{maskedIdentifier:'1234'}),account('ali','wallet')],[observation('b','bank',{relatedReference:'x',occurredAt:'2026-10-08T12:00:00Z'}),observation('w','ali',{relatedReference:'x',paymentAccountHint:'1234',occurredAt:'2026-10-08T10:00:00Z'})],{balanceSnapshots:[{id:'snap2',financialAccountId:'bank',asOf:'2026-10-08T11:00:00Z',balanceMinor:'1000',currency:'CNY',source:'manual'}]}));
assert.equal(view.accountStats.bank.balanceMinor,'900','bank movement uses bank source booking time');
view=buildFinanceView(ledger([account('bank'),account('card','credit_card')],[observation('cardbuy','card',{amountMinor:'500'}),observation('repayment','bank',{kind:'debt_payment',amountMinor:'530',principalMinor:'500',interestMinor:'20',feeMinor:'10'})]));
assert.equal(view.fundingBreakdown.CNY.creditFundedConsumptionMinor,'500');
assert.equal(view.fundingBreakdown.CNY.loanPrincipalPaidMinor,'500');
assert.equal(view.fundingBreakdown.CNY.interestPaidMinor,'20');
assert.equal(view.fundingBreakdown.CNY.feesPaidMinor,'10');
view=buildFinanceView(ledger([account('bank')],[observation('buy','bank',{category:'Food'}),observation('return','bank',{kind:'refund',direction:'credit',category:'Refunds',amountMinor:'20',relatedReference:'buy'})]));
assert.equal(view.categoryTotals.CNY.Food,'80','linked refunds reduce original purchase category');
view=buildFinanceView(ledger([account('bank'),account('ali','wallet')],[observation('b','bank',{relatedReference:'r'}),observation('w','ali',{relatedReference:'r',paymentAccountHint:'bank'})]),{accountIds:['ali']});
assert.equal(view.fundingTotals.bank.CNY,'100','channel selection still exposes the actual funding account');
assert.equal(view.currencyTotals.CNY.cashOutMinor,'0','unselected funding account cash flow is excluded');
view=buildFinanceView(ledger([account('__proto__')],[observation('safe','__proto__',{category:'constructor'})]));
assert.equal(view.accountStats['__proto__'].cashOutMinor,'100');
assert.equal(view.categoryTotals.CNY.constructor,'100','untrusted names cannot collide with object prototypes');
view=buildFinanceView(ledger([account('bank','bank',{openingBalanceMinor:'1000',openingDate:'2026-10-01'}),account('wallet','wallet')],[observation('bank-debit','bank'),observation('channel','wallet',{paymentAccountHint:'bank'})]));
assert.equal(view.transactions.length,2,'funding hint without a shared reference requires review');
assert.equal(view.accountStats.bank.balanceMinor,'900','ambiguous channel source cannot invent a second bank debit');
assert.ok(view.unresolvedAssociations.some(a=>a.reason==='insufficient_reference'&&a.candidateObservationIds.includes('bank-debit')));
view=buildFinanceView(ledger([account('bank')],[],{balanceSnapshots:[{id:'older',financialAccountId:'bank',currency:'CNY',asOf:'2026-10-08T00:00:00Z',balanceMinor:'1000',source:'manual',createdAt:'2026-10-08T01:00:00Z'},{id:'newer',financialAccountId:'bank',currency:'CNY',asOf:'2026-10-08T00:00:00Z',balanceMinor:'2000',source:'manual',createdAt:'2026-10-08T02:00:00Z'}]}));
assert.equal(view.accountStats.bank.balanceMinor,'2000','latest explicit calibration wins equal asOf');
view=buildFinanceView(ledger([account('bank')],[observation('same-time1','bank',{balanceMinor:'1000'}),observation('same-time2','bank',{balanceMinor:'900'})]));
assert.equal(view.accountStats.bank.balanceMinor,null,'conflicting same-time statement balances have no inferred ordering');
assert.ok(view.unresolvedAssociations.some(a=>a.reason==='ambiguous_balance_anchor'));
view=buildFinanceView(ledger([account('bank','bank',{openingBalanceMinor:'1000',openingDate:'2026-10-08'})],[observation('early','bank',{occurredAt:'2026-10-08T01:00:00+08:00'})]));
assert.equal(view.accountStats.bank.balanceMinor,'900','opening dates use statement calendar dates across timezones');
const original=observation('annotated','bank',{kind:'unknown',category:'',amountMinor:'530'});
const annotatedLedger=ledger([account('bank')],[original],{annotations:[{id:'a1',observationId:'annotated',revision:'1',patch:{kind:'expense',category:'Food'}},{id:'a2',observationId:'annotated',revision:'2',patch:{kind:'debt_payment',category:'Mortgage',principalMinor:'500',interestMinor:'20',feeMinor:'10'}}]});
view=buildFinanceView(annotatedLedger);
assert.equal(view.categoryTotals.CNY.Mortgage,'30','latest account-owned annotation corrects purpose and monthly split');
assert.equal(view.transactions[0].sources[0].kind,'unknown','original observation is retained verbatim');
assert.equal(original.kind,'unknown');assert.equal(view.transactions[0].appliedAnnotations[0].id,'a2');
view=buildFinanceView(ledger([account('bank','bank',{maskedIdentifier:'尾号1234'}),account('wallet','wallet')],[observation('decorated-bank','bank',{relatedReference:'shared'}),observation('decorated-wallet','wallet',{relatedReference:'shared',paymentAccountHint:'1234'})]));assert.equal(view.transactions.length,1,'decorated masked identifiers support exact tail evidence');
view=buildFinanceView(ledger([account('usd','bank',{currency:'USD',maskedIdentifier:'1234',openingBalanceMinor:'1000',openingDate:'2026-10-01'}),account('wallet','wallet')],[observation('cny-wallet','wallet',{paymentAccountHint:'1234'})]));assert.equal(view.accountStats.usd.balanceMinor,'1000','foreign currency hint cannot modify another currency balance');assert.ok(view.unresolvedAssociations.some(a=>a.reason==='unresolved_funding_account'));
view=buildFinanceView(ledger([account('loan','loan',{openingBalanceMinor:'10000',openingDate:'2026-10-01'})],[observation('loan-repay','loan',{kind:'debt_payment',direction:'credit',amountMinor:'10230',principalMinor:'10000',interestMinor:'200',feeMinor:'30'})]));assert.equal(view.accountStats.loan.balanceMinor,'0','loan outstanding balance decreases by principal only');
view=buildFinanceView(ledger([account('card','credit_card'),account('wallet','wallet')],[observation('orig','card',{sourceTransactionId:'original',category:'Food'}),observation('refund-other','wallet',{kind:'refund',direction:'credit',relatedReference:'original',category:'Refunds',amountMinor:'20'})]),{accountIds:['wallet']});assert.equal(view.categoryTotals.CNY.Food,'-20');assert.equal(view.transactions[0].relatedTransactionId,'orig','refund links are resolved before account selection');
const payment={kind:'debt_payment',amountMinor:'10230',principalMinor:'10000',interestMinor:'200',feeMinor:'30'};
view=buildFinanceView(ledger([account('bank'),account('loan','loan',{openingBalanceMinor:'10000',openingDate:'2026-10-01'})],[observation('payment-bank','bank',{...payment,relatedReference:'repayment-reference'}),observation('payment-loan','loan',{...payment,direction:'credit',relatedReference:'repayment-reference'})]));assert.equal(view.currencyTotals.CNY.consumptionMinor,'230','one reference-backed repayment has one interest and fee cost');assert.equal(view.fundingBreakdown.CNY.loanPrincipalPaidMinor,'10000');assert.equal(view.accountStats.loan.balanceMinor,'0');assert.equal(view.currencyTotals.CNY.cashOutMinor,'10230');
view=buildFinanceView(ledger([account('bank'),account('loan','loan')],[observation('payment-bank','bank',payment),observation('payment-loan','loan',{...payment,direction:'credit'})],{links:[{id:'payment-link',type:'transfer',observationIds:['payment-bank','payment-loan'],status:'active'}]}));assert.equal(view.currencyTotals.CNY.consumptionMinor,'230','confirmed repayment legs retain one financing cost');assert.equal(view.fundingBreakdown.CNY.loanPrincipalPaidMinor,'10000');
view=buildFinanceView(ledger([account('bank'),account('wallet','wallet')],[observation('manual-bank','bank'),observation('manual-wallet','wallet')],{links:[{id:'manual-duplicate',type:'duplicate',observationIds:['manual-bank','manual-wallet'],status:'active'}]}));assert.equal(view.currencyTotals.CNY.cashOutMinor,'100','manual duplicate supplies evidence that wallet is a payment channel');assert.equal(view.accountStats.wallet.cashOutMinor,'0');
view=buildFinanceView(ledger([account('bank'),account('wallet','wallet')],[observation('purchase','bank',{category:'Food'}),observation('return-wallet','wallet',{kind:'refund',direction:'credit',category:'Refunds',amountMinor:'20'}),observation('return-bank','bank',{kind:'refund',direction:'credit',category:'Refunds',amountMinor:'20'})],{links:[{id:'refund-duplicate',type:'duplicate',observationIds:['return-wallet','return-bank'],status:'active'},{id:'refund-reference',type:'refund',observationIds:['return-bank','purchase'],status:'active'}]}));assert.equal(view.categoryTotals.CNY.Food,'80','manual refund relation can address any group source');
view=buildFinanceView(ledger([account('loan','loan',{openingBalanceMinor:'10000',openingDate:'2026-10-01'})],[observation('unsplit-loan','loan',{kind:'debt_payment',direction:'credit',amountMinor:'1000'})]));assert.equal(view.accountStats.loan.balanceMinor,null,'unsplit loan payment makes projected principal unknown');
view=buildFinanceView(ledger([account('bank'),account('loan','loan')],[observation('loan-first','loan',{...payment,direction:'credit',relatedReference:'reference'}),observation('bank-second','bank',{...payment,relatedReference:'reference'})]));assert.equal(view.fundingTotals.bank.CNY,'230','repayment funding comes from cash source independent of observation ordering');
const many=Array.from({length:6000},(_,i)=>observation('many-'+i,'bank',{amountMinor:String(i+1)}));
const started=performance.now();view=buildFinanceView(ledger([account('bank')],many));
assert.equal(view.transactions.length,6000);assert.equal(view.currencyTotals.CNY.consumptionMinor,'18003000');
assert.ok(performance.now()-started<2000,'6000 independent transactions must not block the UI with a full pair scan');
console.log('6000-row finance view completed in '+Math.round(performance.now()-started)+' ms');
console.log('personal finance ledger accounting and evidence tests passed');
