'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8');
const styles = fs.readFileSync(path.join(__dirname, 'index.scss'), 'utf8');
const config = fs.readFileSync(path.join(__dirname, 'index.config.ts'), 'utf8');
const apiSource = fs.readFileSync(path.join(__dirname, '..', '..', 'utils', 'api.ts'), 'utf8');
const basketSource = fs.readFileSync(path.join(__dirname, '..', '..', 'components', 'QuestionBasketOverlay.tsx'), 'utf8');
const loader = source.match(/const loadQuestionAssets = async \(nextItems: PaperItem\[\], session: any\) => \{([\s\S]*?)\n  \};\n\n  const reload/);
const assetSelectionBlock = source.match(/function questionAssetRequests\(item: PaperItem\)[\s\S]*?\n\}/);
const afterAnswerBlock = source.match(/const renderPaperItem = \(item: PaperItem, index: number\) => \{([\s\S]*?)\n  \};/);
const endAnswerBlock = source.match(/\{answerPosition === 'end' && items\.length \? ([\s\S]*?) : null\}\s*<View className='paper-export-actions'/);
const editorRenderBlock = afterAnswerBlock;
const downloadBlock = source.match(/const download = async \(task: PaperTask\) => \{([\s\S]*?)\n  \};/);

assert.ok(loader, 'question-paper media loading must remain a separate lifecycle from the page reload');
assert.ok(assetSelectionBlock, 'question-paper media selection must remain an explicit, testable boundary');
assert.match(source, /questionDisplayRuntime/, 'question-paper must import the shared question display projection');
assert.match(assetSelectionBlock[0], /const display = createQuestionDisplay\(item\)/, 'question-paper media selection must project the exact rendered question first');
assert.match(assetSelectionBlock[0], /questionAssetKeys\(display\)/, 'question-paper media selection must inspect the complete rendered projection');
assert.doesNotMatch(assetSelectionBlock[0], /item\.(?:stemPreview|options|answer|explanation|richContent)/, 'question-paper media selection must not inspect parallel raw payload fields');
assert.match(source, /requestedQuestionAssetsRef = useRef<Set<string>>\(new Set\(\)\)/, 'one mounted editor must remember every questionId + assetKey request');
assert.match(source, /pageActiveRef = useRef\(true\)/, 'late media responses must be rejected after the editor unmounts');
assert.match(loader[1], /authSessionRuntime\.isSameSession\(session\)/, 'late media responses must be rejected after the authenticated account changes');
assert.match(loader[1], /if \(!pageActiveRef\.current \|\| !authSessionRuntime\.isSameSession\(session\)\) return/, 'media writes must share the mounted-page and session-generation guard');
assert.match(loader[1], /requestedQuestionAssetsRef\.current\.has\(requestKey\)/, 'overlapping loads must ignore an already requested question asset');
assert.match(loader[1], /requestedQuestionAssetsRef\.current\.add\(requestKey\)/, 'dedupe must be reserved before the POST starts');
assert.match(source, /const QUESTION_ASSET_CONCURRENCY = 4;/, 'question media loading must declare a small concurrency ceiling');
assert.doesNotMatch(loader[1], /Promise\.all\(requests\.map/, 'question media loading must not start every selected asset at once');
assert.match(loader[1], /Math\.min\(QUESTION_ASSET_CONCURRENCY, requests\.length\)/, 'the worker pool must never exceed the media concurrency ceiling');
assert.match(loader[1], /await Promise\.all\(workers\)/, 'only the bounded worker pool may run concurrently');
assert.strictEqual((loader[1].match(/requestQuestionAssetDelivery/g) || []).length, 1, 'one questionId + assetKey may issue at most one POST');
assert.match(loader[1], /const deliveryId = delivery\.deliveryId/, 'queued and leased deliveries must retain the original delivery id');
assert.match(loader[1], /\['queued', 'leased'\]\.includes\(delivery\.status\)/, 'only pending delivery states may be polled');
assert.match(loader[1], /attempt < QUESTION_ASSET_POLL_ATTEMPTS/, 'delivery polling must have a fixed upper bound');
assert.match(loader[1], /readQuestionAssetDelivery\(token, deliveryId\)/, 'pending delivery status must be read by the original id instead of preparing again');
assert.match(loader[1], /downloadQuestionAssetDelivery\(token, deliveryId\)/, 'the ready asset must download through that same delivery');
assert.match(loader[1], /let requestCompleted = false;/, 'one asset attempt must distinguish a completed download from every failure exit');
assert.match(loader[1], /requestCompleted = true;/, 'only a completed asset download may keep its request key reserved');
assert.match(loader[1], /finally \{\s*if \(!requestCompleted\) requestedQuestionAssetsRef\.current\.delete\(requestKey\);\s*\}/, 'preparation, polling, timeout, download, and exception failures must release the request key');
assert.strictEqual((loader[1].match(/requestedQuestionAssetsRef\.current\.delete\(requestKey\)/g) || []).length, 1, 'all asset failure exits must share one request-key cleanup path');
assert.match(source, /usePullDownRefresh/, 'a deliberate native pull-to-refresh gesture must retry a released media request');
assert.match(source, /Taro\.stopPullDownRefresh\(\)/, 'native pull-to-refresh must always finish visibly');
assert.doesNotMatch(source, /className='compact-button' onClick=\{reload\}/, 'the editor must not keep a permanent question refresh button');
assert.doesNotMatch(source, /className='preview-refresh'/, 'export records must refresh with the same native gesture rather than another permanent button');
assert.doesNotMatch(source, /ScrollView/, 'the editor must use the native page scroll instead of a nested scroll container');
assert.doesNotMatch(styles, /\.paper-item-list\s*\{[^}]*max-height/s, 'the editor list must never be clipped to an internal maximum height');
assert.match(config, /enablePullDownRefresh:\s*true/, 'the page configuration must enable native pull-to-refresh');
assert.doesNotMatch(source, /assetRetryRef/, 'question media failure must not retain the old whole-page retry counter');
assert.doesNotMatch(source, /setTimeout\(\(\) => \{ void reload\(\); \}, 1500\)/, 'question media failure must never restart the question list and POST every asset again');

assert.match(source, /function isPaperScore\(value: unknown\): value is number/, 'saved paper scores need one explicit validation contract');
assert.match(source, /normalizePaperLayoutField\('score', value\)\.valid/, 'draft restore must share the interactive cloud score constraint');
assert.match(source, /score: isPaperScore\(saved\.items\[index\]\.score\)/, 'draft restore must use the same one-decimal paper score contract');
assert.doesNotMatch(source, /score: Number\.isSafeInteger\(saved\.items\[index\]\.score\)/, 'draft restore must not discard a valid decimal score');
assert.match(source, /const handleLayoutFieldEdit = /, 'score and section editors must share one event boundary');
assert.match(source, /applyPaperLayoutFieldEdit\(item, \{ field, value, phase \}\)/, 'input and blur events must use the tested workflow normalization');
assert.match(source, /onInput=\{event => handleLayoutFieldEdit\(item, 'score', event\.detail\.value, 'input'\)\}/, 'score input must validate while editing');
assert.match(source, /onBlur=\{event => handleLayoutFieldEdit\(item, 'score', event\.detail\.value, 'blur'\)\}/, 'score blur must request the shared visible error behavior');
assert.match(source, /onInput=\{event => handleLayoutFieldEdit\(item, 'sectionTitle', event\.detail\.value, 'input'\)\}/, 'section input must validate while editing');
assert.match(source, /onBlur=\{event => handleLayoutFieldEdit\(item, 'sectionTitle', event\.detail\.value, 'blur'\)\}/, 'section blur must commit only a normalized title');
assert.match(source, /validateAndNormalizePaperLayout\(\{ questionIds, items: layoutInputItems \}\)/, 'submission must validate the complete edited layout before creating a draft');
assert.match(source, /const groupedItems = useMemo\(\(\) => \{/, 'the editor must derive ordered paper sections from the composed items');
assert.match(source, /groupedItems\.map\(group => <View key=\{group\.title\} className='paper-section'>/, 'the selected-question preview must render actual section boundaries');
assert.match(styles, /\.paper-section-head\s*\{/, 'paper sections need a visible heading layout');
assert.match(source, /const PAPER_TASK_POLL_INTERVAL_MS = \d+;/, 'pending export tasks need a bounded polling cadence');
assert.match(source, /const hasPendingTask = taskState\.tasks\.some\(isPendingPaperTask\)/, 'automatic polling must only run while a confirmed task is pending');
assert.match(source, /const timer = setInterval\(\(\) => \{ void refreshTasks\(\); \}, PAPER_TASK_POLL_INTERVAL_MS\)/, 'pending export tasks must refresh automatically');
assert.match(source, /return \(\) => clearInterval\(timer\)/, 'automatic export polling must stop when no longer mounted or pending');
assert.match(source, /authSessionRuntime\.isSameSession\(session\)/, 'automatic task refresh must reject responses from an obsolete login session');
assert.match(source, /const FORMULA_RENDERING_LABEL = String\.fromCharCode\(20844, 24335, 65306, 20860, 23481, 25490, 29256\);/, 'the miniapp must describe formula output as compatible layout');
assert.doesNotMatch(source, /String\.fromCharCode\(20844, 24335, 65306, 30690, 37327, 25490, 29256\)/, 'the miniapp must not promise vector formula layout');
assert.match(source, /statusText\.timed_out\s*=\s*'\\u5df2\\u8d85\\u65f6'/, 'timed-out export tasks must use a readable localized status label');

assert.ok(downloadBlock, 'completed-task download must remain an explicit interaction boundary');
assert.match(downloadBlock[1], /if \(!task\.taskId \|\| taskBusyId\) return;/, 'download must reject repeated taps while another task action is busy');
assert.match(downloadBlock[1], /setTaskBusyId\(task\.localId\)/, 'download must expose its busy state to the task button');
assert.match(downloadBlock[1], /finally \{ setTaskBusyId\(''\); \}/, 'download must always release its busy lock');

assert.match(apiSource, /listQuestionPreviewsByIds/, 'the miniapp API must expose exact basket hydration over the cloud authority');
assert.match(apiSource, /fetchQuestionPreviewsByIds/, 'exact basket hydration must paginate instead of trusting the current browse page');
assert.match(apiSource, /pageSize:\s*40/, 'exact basket hydration must use the proven bounded browse page size instead of a 200-question request that times out in WeChat');
assert.doesNotMatch(apiSource, /pageSize:\s*200/, 'exact basket hydration must not issue the 200-question request that timed out in the real WeChat runtime');
assert.match(source, /miniappCloudBusinessApi\.listQuestionPreviewsByIds/, 'question-paper content must restore the complete selected id set from cloud authority');
assert.doesNotMatch(source, /questionBasketStore\.replaceQuestions\(listed\)/, 'a paper reload must not prune basket metadata to one cloud page');
assert.match(basketSource, /onResolveQuestions/, 'the floating basket must support cloud hydration after app restart or filter changes');
assert.match(basketSource, /resolutionState === 'loading'/, 'paper entry must stay disabled while missing basket questions are being recovered');
assert.match(basketSource, /authoritativeUnavailableIds/, 'only an exhausted cloud lookup may label a basket id unavailable');
assert.match(source, /questionBasketStore\.readPaperSelection\(\)/, 'the editor must restore the selected basket subset rather than silently using every basket item');
assert.match(source, /const selectedIds = handoff \? handoff\.selectedIds : currentBasket\.ids/, 'an explicit empty handoff must not fall back to every basket item');
assert.match(source, /questionBasketStore\.removeMany\(\[id\]\)/, 'removing a paper item must also update the shared basket');
assert.match(source, /reconcilePaperItemsWithBasket/, 'basket removals must preserve the paper editor\'s deliberate custom ordering');
assert.doesNotMatch(source, /\.sort\(\(left, right\) => Number\(order\.get\(left\.id\)\)/, 'a basket revision must not silently overwrite the editor\'s custom order');
const failedCatalogBlock = source.match(/if \(!response\.success\) \{([\s\S]*?)\n\s*return;\n\s*\}/);
assert.ok(failedCatalogBlock, 'question catalog failure must remain an explicit branch');
assert.doesNotMatch(failedCatalogBlock[1], /setItems\(\[\]\)/, 'a transient cloud failure must not clear the current paper composition');
assert.match(source, /catalogLoaded/, 'draft persistence must know whether a trustworthy question catalog has loaded');
assert.match(source, /if \(!editorKey \|\| loading \|\| !catalogLoaded\) return;/, 'an initial catalog failure must never overwrite a saved paper draft with an empty array');
assert.match(source, /unavailableSelectionIds/, 'the editor must explicitly detect selected questions unavailable in the current catalog');
assert.match(source, /<QuestionBasketOverlay/, 'the editor must keep the global basket reachable');
assert.match(source, /onBeginPaper=\{applyBasketSelection\}/, 'choosing another basket subset inside the editor must apply in place');
assert.match(source, /\[basketState\.revision, loading\]/, 'basket removal and clearing must update the mounted editor');
assert.doesNotMatch(source, /createQuestionBasketRuntime/, 'the editor must not create a second page-local basket runtime');
assert.match(source, /miniappCloudBusinessApi\.createPaperExportTask/, 'paper export behavior must remain available');
assert.match(source, /<RichText/, 'the editor must still render resolved rich media');
assert.ok(editorRenderBlock, 'the selected-question editor must remain an explicit rendering boundary');
assert.match(editorRenderBlock[0], /const display = createQuestionDisplay\(item\)/, 'each selected question must use one shared display projection');
assert.match(editorRenderBlock[0], /miniRichNodes\(display\.stem, assetPaths\)/, 'question stems must render the shared display projection');
assert.match(editorRenderBlock[0], /columnsForOptions\(display\.options\)/, 'option layout must use the shared desktop-compatible column rule');
assert.match(editorRenderBlock[0], /paper-options columns-/, 'options must render in a responsive 1\/2\/4-column grid');
assert.match(editorRenderBlock[0], /paper-option-label[^>]*>\{option\.label \+ '\.'\}/, 'each option must retain an independent A. label cell');
assert.match(editorRenderBlock[0], /miniRichNodes\(option\.content, assetPaths\)/, 'option bodies must render projected rich content separately from labels');
assert.match(source, /function questionSourceLabel\(question: (?:QuestionPreview|PaperItem)\)/, 'paper source display must have one desktop-compatible composition boundary');
for (const field of ['sourceLabel', 'source', 'region', 'school', 'examType', 'examYear']) {
  assert.match(source, new RegExp(`${field}\\?: string`), `paper question types must retain ${field}`);
  assert.match(source, new RegExp(`${field}: question!\\.${field}`), `paper composition must preserve ${field} from the cloud preview`);
}
assert.match(editorRenderBlock[0], /const sourceLabel = questionSourceLabel\(item\)/, 'paper cards must compose the complete source label before rendering');
assert.match(editorRenderBlock[0], /'\\u6765\\u6e90\\uff1a' \+ sourceLabel/, 'paper cards must render the composed source rather than the raw source field alone');
for (const [position, block] of [['after', afterAnswerBlock], ['end', endAnswerBlock]]) {
  assert.ok(block, `${position} answer layout must remain an explicit rendering boundary`);
  assert.match(block[1], /const display = createQuestionDisplay\(item\)/, `${position} answer layout must use the shared display projection`);
  assert.match(block[1], /<RichText[^>]*nodes=\{miniRichNodes\(display\.answer \|\|[^,]+, assetPaths\)\}/, `${position} answer layout must resolve projected answer media through RichText`);
  assert.match(block[1], /<RichText[^>]*nodes=\{miniRichNodes\(display\.explanation, assetPaths\)\}/, `${position} answer layout must resolve projected explanation media through RichText`);
}

assert.strictEqual((source.match(/className='paper-overview'/g) || []).length, 1, 'question count, total score, type and difficulty must appear in one overview only');
assert.doesNotMatch(source, /paper-section-outline/, 'the editor must not repeat a separate section outline above the real question sections');
assert.doesNotMatch(source, /distributionSummary/, 'the old standalone distribution summary must be removed');
assert.match(source, /paper-task-progress-track/, 'each export task card must expose progress');
assert.match(source, /paper-task-progress-fill/, 'task progress needs a visible determinate fill');
assert.match(source, /taskSyncState === 'offline'/, 'export history must distinguish an offline refresh from a failed export task');
assert.match(source, /className=\{'task-item status-' \+ task\.status\}/, 'task cards must expose status-specific styling');
assert.match(styles, /\.task-item\s*\{/, 'export history cards need a complete card layout');
assert.match(styles, /\.paper-task-progress-track\s*\{/, 'export progress needs a track style');
assert.match(styles, /\.paper-task-progress-fill\s*\{/, 'export progress needs a fill style');
assert.match(styles, /\.task-actions\s*\{[^}]*flex-wrap:\s*wrap/s, 'task actions must wrap on narrow screens');
assert.match(styles, /padding:[^;]*calc\((?:1[89]\d|2\d\d)rpx \+ env\(safe-area-inset-bottom\)\)/, 'the last paper content must clear the floating basket and safe area');

console.log('miniapp question paper cloud delivery lifecycle checks passed');
