const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const express = require('express');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'gateway-relay-auth-'));
process.env.GATEWAY_DB_PATH = path.join(root, 'gateway.db');
process.env.GEWU_CLOUD_RELAY_HOST_TOKEN = 'test-host-secret';
const { initDatabase, closeDatabase, getDb } = require('../db/database');
const router = require('./cloudRelay');
const pairingRouter = require('./desktopPairing');

(async () => {
  initDatabase();
  const app = express(); app.use(express.json());
  app.use((req, _res, next) => { if (req.headers['x-test-user']) req.user = JSON.parse(req.headers['x-test-user']); next(); });
  app.use('/api/cloud', router);
  app.use('/api/desktop-pairing', pairingRouter);
  const server = app.listen(0); const base = `http://127.0.0.1:${server.address().port}/api/cloud`;
  const call = (url, options = {}) => fetch(base + url, { ...options, signal: AbortSignal.timeout(3000), headers: { 'content-type': 'application/json', ...(options.headers || {}) } });
  const pairingCall=(url,body)=>fetch(`http://127.0.0.1:${server.address().port}/api/desktop-pairing${url}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
  assert.strictEqual((await pairingCall('/start',{phone:'13800138000',deviceId:'pair-http-d1',secret:'a'.repeat(64)})).status,200);
  assert.strictEqual((await pairingCall('/start',{phone:'23800138000',deviceId:'pair-http-d2',secret:'a'.repeat(64)})).status,403);
  assert.strictEqual((await call('/snapshots/publish', { method: 'POST', body: '{}' })).status, 403);
  assert.strictEqual((await call('/tasks')).status, 403);
  assert.strictEqual((await call('/tasks/x/complete', { method: 'POST', headers: { 'x-gewu-host-token': 'wrong' }, body: '{}' })).status, 403);
  assert.strictEqual((await call('/host/heartbeat', { method: 'POST', headers: { 'x-gewu-host-token': 'test-host-secret' }, body: JSON.stringify({ hostDeviceId: 'host1' }) })).status, 200);
  const now = new Date().toISOString();
  getDb().prepare("INSERT INTO miniapp_tasks (id,task_type,status,payload,created_by,created_at,updated_at) VALUES ('task1','question-paper','pending_host','{}','u1',?,?)").run(now, now);
  assert.strictEqual((await call('/tasks', { headers: { 'x-gewu-host-token': 'test-host-secret' } })).status, 200);
  assert.strictEqual((await call('/tasks/task1/complete', { method: 'POST', headers: { 'x-gewu-host-token': 'test-host-secret' }, body: '{}' })).status, 200);
  const approved = id => JSON.stringify({ id, user_type: 'student', student_id: id, review_status: 'approved', status: 1, login_enabled: 1 });
  const teacher = id => JSON.stringify({ id, user_type:'teacher', teacher_id:'t1', review_status:'approved', status:1, login_enabled:1 });
  assert.strictEqual((await call('/desktop-sync/devices/register',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d1'},body:'{}'})).status,200);
  getDb().prepare(`INSERT INTO desktop_device_pairings(id,device_id,device_name,phone,secret_hash,pairing_code,status,expires_at,user_id,created_at,updated_at)
    VALUES('pair-cloud-d1','cloud-d1','PC','13000000000','hash','123456','approved',?,'teacher1',?,?)`).run(new Date(Date.now()+600000).toISOString(),now,now);
  const legalChanges=[{id:'op1',table:'courses',action:'update',data:{id:'c1'}}];
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d1'},body:JSON.stringify({pendingChanges:legalChanges})})).status,200);
  const desktopTask=getDb().prepare("SELECT * FROM miniapp_tasks WHERE task_type='desktop-sync'").get();
  assert.ok(JSON.parse(desktopTask.payload).relayAssertion.signature,'formal gateway must persist a server-signed relay assertion');
  getDb().prepare("UPDATE desktop_device_pairings SET expires_at='2000-01-01T00:00:00.000Z' WHERE id='pair-cloud-d1'").run();
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d1'},body:JSON.stringify({pendingChanges:legalChanges})})).status,200,'approved pairing remains durable after request-window expiry');
  getDb().prepare("UPDATE desktop_device_pairings SET status='pending' WHERE id='pair-cloud-d1'").run();
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d1'},body:JSON.stringify({pendingChanges:legalChanges})})).status,403);
  getDb().prepare("UPDATE desktop_device_pairings SET status='approved' WHERE id='pair-cloud-d1'").run();
  const pendingPoll=await call(`/desktop-sync/requests/${desktopTask.id}/result`,{headers:{'x-test-user':teacher('teacher1')}});assert.strictEqual(pendingPoll.status,200);assert.strictEqual((await pendingPoll.json()).request.status,'pending_host');
  getDb().prepare("UPDATE miniapp_tasks SET status='completed',result_payload=? WHERE id=?").run(JSON.stringify({applied:1}),desktopTask.id);
  const completedPoll=await call(`/desktop-sync/requests/${desktopTask.id}/result`,{headers:{'x-test-user':teacher('teacher1')}});assert.strictEqual((await completedPoll.json()).request.result_payload.applied,1);
  assert.strictEqual((await call(`/desktop-sync/requests/${desktopTask.id}/result`,{headers:{'x-test-user':teacher('teacher2')}})).status,404);
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',body:JSON.stringify({deviceId:'cloud-d1'})})).status,401);
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher2'),'x-device-id':'cloud-d1'},body:JSON.stringify({pendingChanges:legalChanges})})).status,403);
  delete process.env.GEWU_CLOUD_RELAY_HOST_TOKEN;
  assert.strictEqual((await call('/desktop-sync/devices/register',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d2'},body:'{}'})).status,200);
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d2'},body:JSON.stringify({pendingChanges:legalChanges})})).status,403);
  const tooMany=Array.from({length:501},(_,i)=>({id:`op${i}`,table:'courses',action:'update',data:{id:`c${i}`}}));
  assert.strictEqual((await call('/desktop-sync/requests',{method:'POST',headers:{'x-test-user':teacher('teacher1'),'x-device-id':'cloud-d1'},body:JSON.stringify({pendingChanges:tooMany})})).status,413);
  process.env.GEWU_CLOUD_RELAY_HOST_TOKEN='test-host-secret';
  assert.strictEqual((await call('/tasks/task1/result', { headers: { 'x-test-user': approved('u2') } })).status, 404);
  assert.strictEqual((await call('/tasks/task1/result', { headers: { 'x-test-user': approved('u1') } })).status, 200);
  getDb().prepare("INSERT INTO miniapp_tasks (id,task_type,status,payload,created_by,created_at,updated_at) VALUES ('task2','question-paper','completed','{}','1',?,?)").run(now, now);
  assert.strictEqual((await call('/tasks/task2/result', { headers: { 'x-test-user': approved(1) } })).status, 200, 'owner ids are normalized as strings in SQL');
  server.close(); closeDatabase(); fs.rmSync(root, { recursive: true, force: true });
  console.log('gateway cloud relay HTTP auth checks passed');
})().catch(err => { console.error(err); process.exit(1); });
