const express=require('express');const jwt=require('jsonwebtoken');const crypto=require('crypto');
const {getDb}=require('../db/database');const {authMiddleware,JWT_SECRET}=require('../middleware/auth');
const {createDesktopPairing,exchangeDesktopPairing,normalizePhone}=require('../services/desktopPairingService');const router=express.Router();
const send=(res,e)=>res.status(e.code==='PAIRING_NOT_FOUND'?404:403).json({success:false,code:e.code||'PAIRING_FAILED'});
router.post('/start',(req,res)=>{try{res.json({success:true,pairing:createDesktopPairing(getDb(),req.body)});}catch(e){send(res,e);}});
router.post('/exchange',(req,res)=>{try{const result=exchangeDesktopPairing(getDb(),req.body),user=getDb().prepare('SELECT * FROM users WHERE id=?').get(result.userId);if(!user||user.review_status!=='approved'||user.login_enabled===0||user.status===0)throw Object.assign(new Error(),{code:'USER_NOT_APPROVED'});const token=jwt.sign({id:user.id,user_type:user.user_type,deviceId:result.deviceId},JWT_SECRET,{expiresIn:'30m'});res.json({success:true,token,userId:user.id,deviceId:result.deviceId,expiresIn:1800});}catch(e){send(res,e);}});
router.get('/pending',authMiddleware,(req,res)=>{if(req.user?.user_type!=='super_admin')return res.status(403).json({success:false,code:'SUPER_ADMIN_REQUIRED'});const limit=Math.min(100,Math.max(1,Number(req.query.pageSize)||20)),offset=(Math.max(1,Number(req.query.page)||1)-1)*limit,search=String(req.query.code||'');const rows=getDb().prepare(`SELECT id,device_id AS deviceId,device_name AS deviceName,phone,pairing_code AS pairingCode,status,expires_at AS expiresAt,created_at AS createdAt FROM desktop_device_pairings WHERE status='pending' AND pairing_code LIKE ? ORDER BY created_at DESC LIMIT ? OFFSET ?`).all(`%${search}%`,limit,offset);res.json({success:true,items:rows});});
function review(status,byCode=false){return[authMiddleware,(req,res)=>{if(req.user?.user_type!=='super_admin')return res.status(403).json({success:false,code:'SUPER_ADMIN_REQUIRED'});const db=getDb(),row=byCode?db.prepare("SELECT * FROM desktop_device_pairings WHERE pairing_code=? AND status='pending' AND expires_at>=?").get(req.params.pairingCode,new Date().toISOString()):db.prepare('SELECT * FROM desktop_device_pairings WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({success:false,code:'PAIRING_NOT_FOUND'});const users=db.prepare("SELECT * FROM users WHERE review_status='approved' AND login_enabled=1 AND status=1").all().filter(u=>normalizePhone(u.phone)===row.phone);if(users.length!==1)return res.status(409).json({success:false,code:'PAIRING_USER_UNRESOLVED'});const now=new Date().toISOString();db.transaction(()=>{db.prepare('UPDATE desktop_device_pairings SET status=?,approved_by=?,user_id=?,updated_at=? WHERE id=?').run(status,req.user.id,users[0].id,now,row.id);if(status==='approved')db.prepare(`INSERT INTO cloud_devices(id,device_name,role,status,owner_user_id,active,created_at,updated_at)VALUES(?,?,?,'active',?,1,?,?)ON CONFLICT(id)DO UPDATE SET owner_user_id=excluded.owner_user_id,active=1,updated_at=excluded.updated_at`).run(row.device_id,row.device_name,'desktop-client',users[0].id,now,now);db.prepare('INSERT INTO authorization_audit_log(id,actor_user_id,target_user_id,action,after_json,created_at)VALUES(?,?,?,?,?,?)').run(crypto.randomUUID(),req.user.id,users[0].id,`desktop-pairing:${status}`,JSON.stringify({pairingId:row.id,deviceId:row.device_id}),now);})();res.json({success:true,status});}];}
router.post('/:id/approve',...review('approved'));router.post('/:id/reject',...review('rejected'));router.post('/code/:pairingCode/approve',...review('approved',true));router.post('/code/:pairingCode/reject',...review('rejected',true));module.exports=router;
