const { Router } = require('express');
const jwt = require('jsonwebtoken');
const { getInstance } = require('../database');
const { authMiddleware, JWT_SECRET } = require('../middleware/auth');
const { createDesktopPairing, exchangeDesktopPairing, normalizePhone } = require('../services/desktopPairingService');
const router = Router();
const send = (res,error) => res.status(error.code === 'PAIRING_NOT_FOUND' ? 404 : 403).json({success:false,code:error.code||'PAIRING_FAILED'});
router.post('/start',(req,res)=>{ try { res.json({success:true,pairing:createDesktopPairing(getInstance().db,{...req.body,deviceId:req.body.deviceId})}); } catch(e){send(res,e);} });
router.post('/exchange',(req,res)=>{ try { const result=exchangeDesktopPairing(getInstance().db,req.body);
  const user=getInstance().db.prepare('SELECT * FROM users WHERE id=? AND deleted=0').get(result.userId);
  if(!user||user.review_status!=='approved'||user.login_enabled===0||user.status===0) throw Object.assign(new Error(),{code:'USER_NOT_APPROVED'});
  const token=jwt.sign({id:user.id,user_type:user.role,deviceId:result.deviceId},JWT_SECRET,{expiresIn:'30m'});
  res.json({success:true,token,userId:user.id,deviceId:result.deviceId,expiresIn:1800}); } catch(e){send(res,e);} });
function review(status){return [authMiddleware,(req,res)=>{try{if(req.authz?.role!=='super_admin')return res.status(403).json({success:false,code:'SUPER_ADMIN_REQUIRED'});
  const db=getInstance();const row=db.db.prepare('SELECT * FROM desktop_device_pairings WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({success:false,code:'PAIRING_NOT_FOUND'});
  const users=db.db.prepare("SELECT * FROM users WHERE deleted=0 AND review_status='approved' AND login_enabled=1").all().filter(u=>normalizePhone(u.phone)===row.phone);
  if(users.length!==1)return res.status(409).json({success:false,code:'PAIRING_USER_UNRESOLVED'});const now=db._now();
  db.db.transaction(()=>{db.db.prepare('UPDATE desktop_device_pairings SET status=?,approved_by=?,user_id=?,updated_at=? WHERE id=?').run(status,req.authz.userId,users[0].id,now,row.id);
    if(status==='approved')db.registerSyncDevice(row.device_id,{ownerUserId:users[0].id,deviceName:row.device_name,role:'desktop-client'});
    db.recordAuthorizationAudit({actorUserId:req.authz.userId,targetUserId:users[0].id,action:`desktop-pairing:${status}`,after:{pairingId:row.id,deviceId:row.device_id}});})();
  res.json({success:true,status});}catch(e){send(res,e);}}];}
router.post('/:id/approve',...review('approved'));router.post('/:id/reject',...review('rejected'));
module.exports=router;
