const assert = require('assert');
const fs = require('fs');
const Module = require('module');
const ts = require('typescript');
const filename = require.resolve('./richQuestionEditorState.ts');
const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const loaded = new Module(filename); loaded._compile(compiled, filename);
const { enqueueEmission, decideExternalSync, clampSelection, requireStoredAssetRef, resolveAssetForDisplay, mapPendingPositions, mapPendingBookmarks, assetDisplayRef, appendSequentialTask } = loaded.exports;
const a = { type: 'doc', content: [{ type: 'paragraph' }] };
const b = { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: 'external' }] }] };
let decision = decideExternalSync(a, a, [JSON.stringify(a)]);
assert.strictEqual(decision.apply, false);
decision = decideExternalSync(b, a, decision.pendingEmissions);
assert.strictEqual(decision.apply, true);
decision = decideExternalSync(a, b, decision.pendingEmissions);
assert.strictEqual(decision.apply, true, 'A after accepted external B must apply');
let queue = enqueueEmission([], a); queue = enqueueEmission(queue, b);
decision = decideExternalSync(a, b, queue);
assert.strictEqual(decision.apply, false, 'delayed A emitted before local B must remain an echo');
decision = decideExternalSync(b, b, queue);
assert.strictEqual(decision.pendingEmissions.length, 0, 'echo B consumes the A,B prefix');
decision = decideExternalSync(a, b, decision.pendingEmissions);
assert.strictEqual(decision.apply, true, 'external A after echo B is no longer stale');
queue = enqueueEmission(enqueueEmission(enqueueEmission([], a), b), a);
decision = decideExternalSync(a, a, queue);
assert.deepStrictEqual(decision.pendingEmissions, [], 'echo A consumes through the newest repeated A emission');
decision = decideExternalSync(b, a, decision.pendingEmissions);
assert.strictEqual(decision.apply, true, 'external B after newest A echo must apply');
assert.deepStrictEqual(clampSelection({ from: 7, to: 20 }, 10), { from: 7, to: 9 });
assert.strictEqual(requireStoredAssetRef('asset-1', 'question-asset://asset-1'), 'question-asset://asset-1');
assert.throws(() => requireStoredAssetRef('asset-1', 'question-asset://asset-2'), /mismatched/);
assert.deepStrictEqual(Array.from(mapPendingPositions(new Map([[1, 4], [2, 4]]), position => position + 1)), [[1, 5], [2, 5]]);
assert.deepStrictEqual(Array.from(mapPendingBookmarks(new Map([[1, { from: 4, to: 7 }], [2, { from: 4, to: 4 }]]), (position, assoc) => position + (assoc === 1 ? 3 : 2))), [[1, { from: 6, to: 10 }], [2, { from: 7, to: 7 }]]);
assert.strictEqual(assetDisplayRef('', 'asset-1'), 'question-asset://asset-1');
resolveAssetForDisplay('question-asset://asset-1', async ref => ref === 'question-asset://asset-1' ? 'data:image/png;base64,AAAA' : '').then(resolved => {
  assert.strictEqual(resolved, 'data:image/png;base64,AAAA');
  return assert.rejects(() => resolveAssetForDisplay('data:image/png;base64,AAAA', async value => value), /persisted/);
}).then(async () => {
  const order = [];
  let releaseFirst; let releaseSecond;
  const first = new Promise(resolve => { releaseFirst = resolve; });
  const second = new Promise(resolve => { releaseSecond = resolve; });
  let drain = appendSequentialTask(Promise.resolve(), async () => { await first; order.push(1); });
  drain = appendSequentialTask(drain, async () => { await second; order.push(2); });
  releaseSecond(); releaseFirst(); await drain;
  assert.deepStrictEqual(order, [1, 2]);
  console.log('rich editor controlled-state tests passed');
});
