const assert = require('node:assert/strict');
const { inferImportedQuestionType: infer, applyImportLabels } = require('./questionImportMetadata');
const { coefficientDifficulty, difficultyLabel, validDifficultyCoefficient } = require('./questionDifficulty');
const single = '\u5355\u9009\u9898', multi = '\u591A\u9009\u9898', judge = '\u5224\u65AD\u9898', experiment = '\u5B9E\u9A8C\u9898', problem = '\u89E3\u7B54\u9898';
for (const answer of ['A', '<p>\u7B54\u6848\uFF1A(A)</p>', '\uFF22']) assert.equal(infer({ answer }), single);
for (const answer of ['AC', 'A\u3001C', 'A B D']) assert.equal(infer({ answer }), multi);
for (const answer of ['\u5BF9', '\u6B63\u786E', '\u9519', '\u9519\u8BEF', '\u221A', '\u00D7', '\u2713', '\u2718', '\u2705', '\u274C', '\u2716\uFE0F', '\u52FE', '\u53C9']) assert.equal(infer({ answer }), judge);
assert.equal(infer({ stem: '\u5B9E\u9A8C\u4E2D', answer: 'v = 2 m/s' }), experiment);
assert.equal(infer({ stem: '\u5B9E\u9A8C\u4E2D', answer: 'AB' }), multi);
for (const answer of ['A = 2', 'a', '', '2 m/s', 'ABC is a formula']) assert.equal(infer({ answer }), problem);
const metadata = { year: '2026-2027', grade: 'g', semester: 's', exam_type: 'e', region: 'r', school: 'school', paper_name: 'paper' };
const candidate = { answer: 'A', source: 'parser', year: 'old', source_info: metadata };
const exam = applyImportLabels(candidate, metadata, 'exam');
for (const key of ['year', 'grade', 'semester', 'exam_type', 'region', 'school']) assert.equal(exam[key], metadata[key]);
assert.equal(exam.source, 'paper');
for (const format of ['lecture', 'topic']) for (const key of ['source', 'year', 'grade', 'semester', 'exam_type', 'region', 'school']) assert.equal(applyImportLabels(candidate, metadata, format)[key], '');
assert.equal(coefficientDifficulty(0), 4); assert.equal(coefficientDifficulty(0.399999), 4);
assert.equal(coefficientDifficulty(0.4), 3); assert.equal(coefficientDifficulty(0.699999), 3);
assert.equal(coefficientDifficulty(0.7), 2); assert.equal(coefficientDifficulty(1), 2);
for (const value of [-0.1, 1.1, NaN, Infinity, '0.7']) assert.equal(validDifficultyCoefficient(value), false);
assert.equal(difficultyLabel(null), '\u672A\u6807\u6CE8');
console.log('import labels and coefficient boundaries passed');
