'use strict';

const V_NEXT_CONTROL_PLANE_REFERENCE_TABLES = Object.freeze([
  'vNext_account_device_links', 'vNext_accounts', 'vNext_authorities',
  'vNext_authorization_audit_events', 'vNext_authorization_command_receipts',
  'vNext_authorization_outbox_events', 'vNext_authorization_policy_publications', 'vNext_bootstrap_consumptions', 'vNext_capability_catalog',
  'vNext_capability_overrides', 'vNext_data_scope_grants', 'vNext_device_installations',
  'vNext_profile_bindings', 'vNext_recent_reauthentication_events', 'vNext_role_grants',
  'vNext_schema_meta', 'vNext_sessions', 'vNext_trust_root_evidence', 'vNext_trusted_devices', 'vNext_verified_contacts',
]);

const NONEMPTY = "CHECK(length(trim(%s))>0)";
const SHA256 = name => `CHECK(typeof(${name})='text' AND length(${name})=64 AND ${name} NOT GLOB '*[^0-9a-f]*')`;
const nullableSha256 = name => `CHECK(${name} IS NULL OR (typeof(${name})='text' AND length(${name})=64 AND ${name} NOT GLOB '*[^0-9a-f]*'))`;
const integerAtLeast = (name, minimum) => `CHECK(typeof(${name})='integer' AND ${name}>=${minimum})`;
const nullableIntegerAtLeast = (name, minimum) => `CHECK(${name} IS NULL OR (typeof(${name})='integer' AND ${name}>=${minimum}))`;
const id = name => `${name} TEXT NOT NULL PRIMARY KEY ${NONEMPTY.replace('%s', name)}`;
const time = name => `${name} TEXT NOT NULL CHECK(julianday(${name}) IS NOT NULL)`;
const version = name => `${name} INTEGER NOT NULL ${integerAtLeast(name, 1)}`;

const POLICY_PUBLICATION_RESULT_SHAPE = `json_type(r.canonical_result_json)='object' AND json_type(r.canonical_result_json,'$.authorityId')='text' AND json_type(r.canonical_result_json,'$.code')='text' AND json_type(r.canonical_result_json,'$.policyContractVersion')='integer' AND json_type(r.canonical_result_json,'$.policyManifestSha256')='text' AND json_type(r.canonical_result_json,'$.policyRevision')='integer' AND json_type(r.canonical_result_json,'$.publicationId')='text' AND json_type(r.canonical_result_json,'$.status')='text' AND json_extract(r.canonical_result_json,'$.authorityId')=NEW.authority_id AND json_extract(r.canonical_result_json,'$.policyContractVersion')=NEW.policy_contract_version AND json_extract(r.canonical_result_json,'$.policyManifestSha256')=NEW.policy_manifest_sha256 AND json_extract(r.canonical_result_json,'$.policyRevision')=NEW.policy_revision AND json_extract(r.canonical_result_json,'$.publicationId')=NEW.publication_id AND json_extract(r.canonical_result_json,'$.status')='accepted' AND (SELECT COUNT(*) FROM json_each(r.canonical_result_json))=7`;
const POLICY_PUBLICATION_STANDARD_RECEIPT = `r.result_code='POLICY_PUBLISHED' AND r.command_type='authorization_policy.publish' AND r.target_kind='authorization_policy' AND r.target_id=NEW.authority_id AND r.expected_row_version=NEW.policy_revision-1 AND r.committed_target_row_version=NEW.policy_revision AND json_extract(r.canonical_result_json,'$.code')='POLICY_PUBLISHED'`;
const POLICY_PUBLICATION_BOOTSTRAP_RECEIPT = `r.result_code='AUTHORITY_BOOTSTRAPPED' AND r.command_type='authority.bootstrap' AND r.target_kind='authority' AND r.target_id=NEW.authority_id AND r.actor_account_id IS NULL AND r.expected_row_version=0 AND r.committed_target_row_version=1 AND NEW.policy_revision=1 AND json_extract(r.canonical_result_json,'$.code')='AUTHORITY_BOOTSTRAPPED' AND EXISTS(SELECT 1 FROM vNext_bootstrap_consumptions m WHERE m.receipt_id=r.receipt_id AND m.authority_id=NEW.authority_id AND m.policy_manifest_sha256=NEW.policy_manifest_sha256 AND r.actor_key='bootstrap:' || m.bootstrap_intent_id AND julianday(NEW.published_at)>=julianday(m.consumed_at))`;
const POLICY_PUBLICATION_INSERT_GUARD_SQL = `BEFORE INSERT ON vNext_authorization_policy_publications BEGIN SELECT CASE WHEN NEW.policy_revision!=(COALESCE((SELECT MAX(policy_revision) FROM vNext_authorization_policy_publications WHERE authority_id=NEW.authority_id),0)+1) THEN RAISE(ABORT,'VNEXT_POLICY_REVISION_CONFLICT') WHEN NOT EXISTS(SELECT 1 FROM vNext_authorities WHERE authority_id=NEW.authority_id AND status='active') OR NOT EXISTS(SELECT 1 FROM vNext_authorization_command_receipts r WHERE r.receipt_id=NEW.receipt_id AND r.authority_id=NEW.authority_id AND r.outcome='accepted' AND r.committed_auth_version IS NULL AND r.committed_access_version IS NULL AND r.committed_revocation_version IS NULL AND julianday(NEW.published_at)>=julianday(r.created_at) AND ${POLICY_PUBLICATION_RESULT_SHAPE} AND (${POLICY_PUBLICATION_STANDARD_RECEIPT} OR ${POLICY_PUBLICATION_BOOTSTRAP_RECEIPT})) THEN RAISE(ABORT,'VNEXT_POLICY_PUBLICATION_RECEIPT_INVALID') WHEN EXISTS(SELECT 1 FROM vNext_authorization_policy_publications WHERE authority_id=NEW.authority_id AND policy_revision=NEW.policy_revision-1 AND policy_contract_version=NEW.policy_contract_version AND policy_manifest_sha256=NEW.policy_manifest_sha256) THEN RAISE(ABORT,'VNEXT_POLICY_UNCHANGED') END; END`;

const STATEMENTS = Object.freeze([
  `CREATE TABLE IF NOT EXISTS vNext_schema_meta (${id('schema_key')} CHECK(schema_key='control-plane-reference'), schema_version INTEGER NOT NULL CHECK(schema_version=5), ${time('applied_at')})`,
  `CREATE TABLE IF NOT EXISTS vNext_authorities (${id('authority_id')}, status TEXT NOT NULL CHECK(status IN ('active','disabled','revoked')), ${time('created_at')}, ${time('updated_at')}, CHECK(julianday(updated_at)>=julianday(created_at)))`,
  `CREATE TABLE IF NOT EXISTS vNext_accounts (${id('account_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, status TEXT NOT NULL CHECK(status IN ('active','disabled','revoked')), ${version('auth_version')}, ${version('access_version')}, ${version('revocation_version')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, CHECK(julianday(updated_at)>=julianday(created_at)), UNIQUE(account_id,authority_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_verified_contacts (${id('contact_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, contact_type TEXT NOT NULL CHECK(contact_type IN ('phone','wechat_openid','wechat_unionid')), normalized_value_hash TEXT NOT NULL ${NONEMPTY.replace('%s', 'normalized_value_hash')}, verification_state TEXT NOT NULL CHECK(verification_state IN ('verified','revoked')), verification_evidence_hash TEXT NOT NULL ${NONEMPTY.replace('%s', 'verification_evidence_hash')}, verified_at TEXT CHECK(verified_at IS NULL OR julianday(verified_at) IS NOT NULL), revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, CHECK(julianday(updated_at)>=julianday(created_at)), CHECK((verification_state='verified' AND verified_at IS NOT NULL AND revoked_at IS NULL) OR (verification_state='revoked' AND verified_at IS NOT NULL AND revoked_at IS NOT NULL)), UNIQUE(authority_id,contact_type,normalized_value_hash), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_role_grants (${id('grant_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, role TEXT NOT NULL CHECK(role IN ('super_admin','teacher','student','family_member')), status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')), ${version('grant_version')}, ${version('row_version')}, ${time('starts_at')}, ends_at TEXT CHECK(ends_at IS NULL OR julianday(ends_at) IS NOT NULL), revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), granted_by_account_id TEXT, ${time('created_at')}, ${time('updated_at')}, CHECK(julianday(updated_at)>=julianday(created_at)), CHECK(ends_at IS NULL OR julianday(ends_at)>julianday(starts_at)), CHECK((status='active' AND revoked_at IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL) OR (status='expired' AND ends_at IS NOT NULL AND revoked_at IS NULL)), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id), FOREIGN KEY(granted_by_account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS vNext_role_grants_one_active_role ON vNext_role_grants(authority_id,account_id,role) WHERE status='active'`,
  `CREATE TABLE IF NOT EXISTS vNext_capability_catalog (capability_id TEXT NOT NULL PRIMARY KEY ${NONEMPTY.replace('%s', 'capability_id')}, status TEXT NOT NULL CHECK(status IN ('active','retired')), surface_mask TEXT NOT NULL ${NONEMPTY.replace('%s', 'surface_mask')}, ${time('created_at')})`,
  `CREATE TABLE IF NOT EXISTS vNext_capability_overrides (${id('override_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, capability_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'capability_id')}, effect TEXT NOT NULL CHECK(effect IN ('allow','deny')), status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')), ${time('starts_at')}, ends_at TEXT CHECK(ends_at IS NULL OR julianday(ends_at) IS NOT NULL), ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK(ends_at IS NULL OR julianday(ends_at)>julianday(starts_at)), CHECK((status='active' AND revoked_at IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL) OR (status='expired' AND ends_at IS NOT NULL AND revoked_at IS NULL)), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id), FOREIGN KEY(capability_id) REFERENCES vNext_capability_catalog(capability_id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS vNext_capability_overrides_one_active_capability ON vNext_capability_overrides(authority_id,account_id,capability_id) WHERE status='active'`,
  `CREATE TABLE IF NOT EXISTS vNext_data_scope_grants (${id('scope_grant_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, scope_type TEXT NOT NULL CHECK(scope_type IN ('teacher_profile','student_profile','school','household','resource_owner')), scope_value_hash TEXT NOT NULL ${NONEMPTY.replace('%s', 'scope_value_hash')}, effect TEXT NOT NULL CHECK(effect IN ('allow','deny')), status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')), ${time('starts_at')}, ends_at TEXT CHECK(ends_at IS NULL OR julianday(ends_at) IS NOT NULL), ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK(ends_at IS NULL OR julianday(ends_at)>julianday(starts_at)), CHECK((status='active' AND revoked_at IS NULL) OR (status='revoked' AND revoked_at IS NOT NULL) OR (status='expired' AND ends_at IS NOT NULL AND revoked_at IS NULL)), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS vNext_data_scope_grants_one_active_scope ON vNext_data_scope_grants(authority_id,account_id,scope_type,scope_value_hash) WHERE status='active'`,
  `CREATE TABLE IF NOT EXISTS vNext_profile_bindings (${id('binding_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, profile_type TEXT NOT NULL CHECK(profile_type IN ('teacher','student')), profile_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'profile_id')}, status TEXT NOT NULL CHECK(status IN ('active','revoked','pending')), evidence_hash TEXT NOT NULL ${NONEMPTY.replace('%s', 'evidence_hash')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK((status='revoked' AND revoked_at IS NOT NULL) OR (status IN ('active','pending') AND revoked_at IS NULL)), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id))`,
  `CREATE UNIQUE INDEX IF NOT EXISTS vNext_profile_bindings_one_active_account_type ON vNext_profile_bindings(authority_id,account_id,profile_type) WHERE status='active'`,
  `CREATE UNIQUE INDEX IF NOT EXISTS vNext_profile_bindings_one_active_profile ON vNext_profile_bindings(authority_id,profile_type,profile_id) WHERE status='active'`,
  `CREATE TABLE IF NOT EXISTS vNext_trusted_devices (${id('device_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, status TEXT NOT NULL CHECK(status IN ('active','risk_limited','revoked','retired')), hardware_evidence_hash TEXT, risk_code TEXT, ${version('credential_version')}, ${version('risk_version')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK((status='revoked' AND revoked_at IS NOT NULL) OR (status!='revoked' AND revoked_at IS NULL)), UNIQUE(device_id,authority_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_device_installations (${id('installation_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, device_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'device_id')}, installation_public_key TEXT NOT NULL ${NONEMPTY.replace('%s', 'installation_public_key')}, key_fingerprint TEXT NOT NULL ${NONEMPTY.replace('%s', 'key_fingerprint')}, status TEXT NOT NULL CHECK(status IN ('active','revoked','retired')), ${version('credential_version')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK((status='revoked' AND revoked_at IS NOT NULL) OR (status!='revoked' AND revoked_at IS NULL)), UNIQUE(installation_id,device_id,authority_id), UNIQUE(authority_id,key_fingerprint), FOREIGN KEY(device_id,authority_id) REFERENCES vNext_trusted_devices(device_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_account_device_links (${id('link_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, device_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'device_id')}, installation_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'installation_id')}, status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')), ${version('auth_version')}, ${version('access_version')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK((status='revoked' AND revoked_at IS NOT NULL) OR (status='expired' AND revoked_at IS NULL) OR status='active'), UNIQUE(authority_id,account_id,installation_id), UNIQUE(link_id,authority_id,account_id,device_id,installation_id), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id), FOREIGN KEY(device_id,authority_id) REFERENCES vNext_trusted_devices(device_id,authority_id), FOREIGN KEY(installation_id,device_id,authority_id) REFERENCES vNext_device_installations(installation_id,device_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_sessions (${id('session_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, account_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'account_id')}, device_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'device_id')}, installation_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'installation_id')}, link_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'link_id')}, session_kind TEXT NOT NULL CHECK(session_kind IN ('online','initialization')), status TEXT NOT NULL CHECK(status IN ('active','revoked','expired')), ${time('issued_at')}, ${time('expires_at')}, revoked_at TEXT CHECK(revoked_at IS NULL OR julianday(revoked_at) IS NOT NULL), ${version('account_auth_version')}, ${version('account_access_version')}, ${version('account_revocation_version')}, ${version('device_credential_version')}, ${version('device_risk_version')}, ${version('installation_credential_version')}, ${version('link_auth_version')}, ${version('link_access_version')}, ${version('link_row_version')}, ${version('row_version')}, ${time('created_at')}, ${time('updated_at')}, CHECK(julianday(expires_at)>julianday(issued_at)), CHECK(julianday(updated_at)>=julianday(created_at)), CHECK(revoked_at IS NULL OR julianday(revoked_at)>=julianday(issued_at)), CHECK((status='revoked' AND revoked_at IS NOT NULL) OR (status IN ('active','expired') AND revoked_at IS NULL)), UNIQUE(session_id,authority_id), FOREIGN KEY(account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id), FOREIGN KEY(device_id,authority_id) REFERENCES vNext_trusted_devices(device_id,authority_id), FOREIGN KEY(installation_id,device_id,authority_id) REFERENCES vNext_device_installations(installation_id,device_id,authority_id), FOREIGN KEY(link_id,authority_id,account_id,device_id,installation_id) REFERENCES vNext_account_device_links(link_id,authority_id,account_id,device_id,installation_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_recent_reauthentication_events (${id('reauth_event_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, session_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'session_id')}, factor_class TEXT NOT NULL CHECK(factor_class IN ('password','passkey','verified_contact')), evidence_sha256 TEXT NOT NULL ${SHA256('evidence_sha256')}, ${version('account_auth_version')}, ${version('account_access_version')}, ${version('account_revocation_version')}, ${version('device_credential_version')}, ${version('device_risk_version')}, ${version('installation_credential_version')}, ${version('link_auth_version')}, ${version('link_access_version')}, ${version('link_row_version')}, ${time('verified_at')}, ${time('expires_at')}, ${time('created_at')}, CHECK(julianday(expires_at)>julianday(verified_at)), FOREIGN KEY(session_id,authority_id) REFERENCES vNext_sessions(session_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_authorization_command_receipts (${id('receipt_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, actor_key TEXT NOT NULL ${NONEMPTY.replace('%s', 'actor_key')}, actor_account_id TEXT, idempotency_key TEXT NOT NULL ${NONEMPTY.replace('%s', 'idempotency_key')}, command_type TEXT NOT NULL ${NONEMPTY.replace('%s', 'command_type')}, target_kind TEXT NOT NULL ${NONEMPTY.replace('%s', 'target_kind')}, target_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'target_id')}, canonical_request_sha256 TEXT NOT NULL ${SHA256('canonical_request_sha256')}, expected_row_version INTEGER ${nullableIntegerAtLeast('expected_row_version', 0)}, outcome TEXT NOT NULL CHECK(outcome IN ('accepted','rejected','noop')), result_code TEXT NOT NULL ${NONEMPTY.replace('%s', 'result_code')}, canonical_result_json TEXT NOT NULL CHECK(json_valid(canonical_result_json)), canonical_result_sha256 TEXT NOT NULL ${SHA256('canonical_result_sha256')}, committed_auth_version INTEGER ${nullableIntegerAtLeast('committed_auth_version', 1)}, committed_access_version INTEGER ${nullableIntegerAtLeast('committed_access_version', 1)}, committed_revocation_version INTEGER ${nullableIntegerAtLeast('committed_revocation_version', 1)}, committed_target_row_version INTEGER ${nullableIntegerAtLeast('committed_target_row_version', 1)}, ${time('created_at')}, UNIQUE(receipt_id,authority_id), UNIQUE(authority_id,actor_key,idempotency_key), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id), FOREIGN KEY(actor_account_id,authority_id) REFERENCES vNext_accounts(account_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_authorization_outbox_events (${id('event_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, receipt_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'receipt_id')}, event_type TEXT NOT NULL ${NONEMPTY.replace('%s', 'event_type')}, aggregate_kind TEXT NOT NULL ${NONEMPTY.replace('%s', 'aggregate_kind')}, aggregate_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'aggregate_id')}, aggregate_version INTEGER NOT NULL ${integerAtLeast('aggregate_version', 1)}, canonical_payload_json TEXT NOT NULL CHECK(json_valid(canonical_payload_json)), payload_sha256 TEXT NOT NULL ${SHA256('payload_sha256')}, ${time('occurred_at')}, UNIQUE(authority_id,receipt_id,event_type,aggregate_kind,aggregate_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id), FOREIGN KEY(receipt_id,authority_id) REFERENCES vNext_authorization_command_receipts(receipt_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_authorization_policy_publications (${id('publication_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, receipt_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'receipt_id')}, policy_revision INTEGER NOT NULL ${integerAtLeast('policy_revision', 1)}, policy_contract_version INTEGER NOT NULL CHECK(typeof(policy_contract_version)='integer' AND policy_contract_version=1), canonical_manifest_json TEXT NOT NULL CHECK(json_valid(canonical_manifest_json) AND json_type(canonical_manifest_json)='object'), policy_manifest_sha256 TEXT NOT NULL ${SHA256('policy_manifest_sha256')}, ${time('published_at')}, UNIQUE(authority_id,policy_revision), UNIQUE(authority_id,receipt_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id), FOREIGN KEY(receipt_id,authority_id) REFERENCES vNext_authorization_command_receipts(receipt_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_authorization_audit_events (${id('event_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, receipt_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'receipt_id')}, reason_code TEXT NOT NULL ${NONEMPTY.replace('%s', 'reason_code')}, context_sha256 TEXT NOT NULL ${SHA256('context_sha256')}, ${time('created_at')}, UNIQUE(authority_id,receipt_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id), FOREIGN KEY(receipt_id,authority_id) REFERENCES vNext_authorization_command_receipts(receipt_id,authority_id))`,
  `CREATE TABLE IF NOT EXISTS vNext_bootstrap_consumptions (${id('marker_key')} CHECK(marker_key='single-authority-bootstrap'), bootstrap_intent_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'bootstrap_intent_id')} UNIQUE, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')} UNIQUE, installation_key_fingerprint TEXT NOT NULL ${SHA256('installation_key_fingerprint')}, policy_manifest_sha256 TEXT NOT NULL ${SHA256('policy_manifest_sha256')}, receipt_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'receipt_id')} UNIQUE, ${time('consumed_at')})`,
  `CREATE TABLE IF NOT EXISTS vNext_trust_root_evidence (${id('evidence_id')}, authority_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'authority_id')}, receipt_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'receipt_id')}, actor_kind TEXT NOT NULL CHECK(actor_kind IN ('deployment_bootstrap','owner_recovery_event')), event_id TEXT NOT NULL ${NONEMPTY.replace('%s', 'event_id')}, assertion_evidence_sha256 TEXT NOT NULL ${SHA256('assertion_evidence_sha256')}, backup_id TEXT, backup_manifest_sha256 TEXT ${nullableSha256('backup_manifest_sha256')}, ${time('created_at')}, UNIQUE(authority_id,receipt_id), UNIQUE(actor_kind,event_id), FOREIGN KEY(authority_id) REFERENCES vNext_authorities(authority_id), FOREIGN KEY(receipt_id,authority_id) REFERENCES vNext_authorization_command_receipts(receipt_id,authority_id), CHECK((actor_kind='deployment_bootstrap' AND backup_id IS NULL AND backup_manifest_sha256 IS NULL) OR (actor_kind='owner_recovery_event' AND backup_id IS NOT NULL AND length(trim(backup_id))>0 AND backup_manifest_sha256 IS NOT NULL)))`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_command_receipts_no_update BEFORE UPDATE ON vNext_authorization_command_receipts BEGIN SELECT RAISE(ABORT,'vNext command receipt is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_command_receipts_no_delete BEFORE DELETE ON vNext_authorization_command_receipts BEGIN SELECT RAISE(ABORT,'vNext command receipt is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_outbox_events_no_update BEFORE UPDATE ON vNext_authorization_outbox_events BEGIN SELECT RAISE(ABORT,'vNext outbox event is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_outbox_events_no_delete BEFORE DELETE ON vNext_authorization_outbox_events BEGIN SELECT RAISE(ABORT,'vNext outbox event is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_policy_publications_insert_guard ${POLICY_PUBLICATION_INSERT_GUARD_SQL}`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_policy_publications_no_update BEFORE UPDATE ON vNext_authorization_policy_publications BEGIN SELECT RAISE(ABORT,'vNext policy publication is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_policy_publications_no_delete BEFORE DELETE ON vNext_authorization_policy_publications BEGIN SELECT RAISE(ABORT,'vNext policy publication is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_audit_events_no_update BEFORE UPDATE ON vNext_authorization_audit_events BEGIN SELECT RAISE(ABORT,'vNext audit is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_authorization_audit_events_no_delete BEFORE DELETE ON vNext_authorization_audit_events BEGIN SELECT RAISE(ABORT,'vNext audit is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_bootstrap_consumptions_insert_guard BEFORE INSERT ON vNext_bootstrap_consumptions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM vNext_authorization_command_receipts r WHERE r.receipt_id=NEW.receipt_id AND r.authority_id=NEW.authority_id AND r.actor_key='bootstrap:'||NEW.bootstrap_intent_id AND r.actor_account_id IS NULL AND r.command_type='authority.bootstrap' AND r.target_kind='authority' AND r.target_id=NEW.authority_id AND r.outcome='accepted' AND r.result_code='AUTHORITY_BOOTSTRAPPED' AND r.expected_row_version=0 AND r.committed_target_row_version=1 AND r.committed_auth_version IS NULL AND r.committed_access_version IS NULL AND r.committed_revocation_version IS NULL AND julianday(NEW.consumed_at)>=julianday(r.created_at) AND json_type(r.canonical_result_json)='object' AND json_type(r.canonical_result_json,'$.authorityId')='text' AND json_type(r.canonical_result_json,'$.code')='text' AND json_type(r.canonical_result_json,'$.policyContractVersion')='integer' AND json_type(r.canonical_result_json,'$.policyManifestSha256')='text' AND json_type(r.canonical_result_json,'$.policyRevision')='integer' AND json_type(r.canonical_result_json,'$.publicationId')='text' AND json_type(r.canonical_result_json,'$.status')='text' AND json_extract(r.canonical_result_json,'$.authorityId')=NEW.authority_id AND json_extract(r.canonical_result_json,'$.code')='AUTHORITY_BOOTSTRAPPED' AND json_extract(r.canonical_result_json,'$.policyContractVersion')=1 AND json_extract(r.canonical_result_json,'$.policyManifestSha256')=NEW.policy_manifest_sha256 AND json_extract(r.canonical_result_json,'$.policyRevision')=1 AND json_extract(r.canonical_result_json,'$.status')='accepted' AND (SELECT COUNT(*) FROM json_each(r.canonical_result_json))=7) THEN RAISE(ABORT,'VNEXT_BOOTSTRAP_MARKER_RECEIPT_INVALID') END; END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_bootstrap_consumptions_no_update BEFORE UPDATE ON vNext_bootstrap_consumptions BEGIN SELECT RAISE(ABORT,'vNext bootstrap consumption is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_bootstrap_consumptions_no_delete BEFORE DELETE ON vNext_bootstrap_consumptions BEGIN SELECT RAISE(ABORT,'vNext bootstrap consumption is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_trust_root_evidence_insert_guard BEFORE INSERT ON vNext_trust_root_evidence BEGIN SELECT CASE WHEN NEW.actor_kind='deployment_bootstrap' AND NOT EXISTS(SELECT 1 FROM vNext_bootstrap_consumptions m WHERE m.authority_id=NEW.authority_id AND m.bootstrap_intent_id=NEW.event_id AND m.receipt_id=NEW.receipt_id AND julianday(NEW.created_at)>=julianday(m.consumed_at)) THEN RAISE(ABORT,'VNEXT_TRUST_ROOT_EVIDENCE_RECEIPT_INVALID') WHEN NEW.actor_kind='owner_recovery_event' AND NOT EXISTS(SELECT 1 FROM vNext_authorization_command_receipts r WHERE r.receipt_id=NEW.receipt_id AND r.authority_id=NEW.authority_id AND r.actor_key='recovery:'||NEW.event_id AND r.actor_account_id IS NULL AND r.command_type='authority.owner_recover' AND r.target_kind='authority' AND r.target_id=NEW.authority_id AND r.outcome='accepted' AND r.result_code='OWNER_RECOVERY_COMPLETED' AND r.expected_row_version IS NULL AND r.committed_target_row_version IS NULL AND r.committed_auth_version IS NULL AND r.committed_access_version IS NULL AND r.committed_revocation_version IS NULL AND julianday(NEW.created_at)>=julianday(r.created_at) AND json_type(r.canonical_result_json)='object' AND json_type(r.canonical_result_json,'$.authorityId')='text' AND json_type(r.canonical_result_json,'$.code')='text' AND json_type(r.canonical_result_json,'$.replacementAccountId')='text' AND json_type(r.canonical_result_json,'$.status')='text' AND json_extract(r.canonical_result_json,'$.authorityId')=NEW.authority_id AND json_extract(r.canonical_result_json,'$.code')='OWNER_RECOVERY_COMPLETED' AND json_extract(r.canonical_result_json,'$.status')='accepted' AND (SELECT COUNT(*) FROM json_each(r.canonical_result_json))=4) THEN RAISE(ABORT,'VNEXT_TRUST_ROOT_EVIDENCE_RECEIPT_INVALID') END; END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_trust_root_evidence_no_update BEFORE UPDATE ON vNext_trust_root_evidence BEGIN SELECT RAISE(ABORT,'vNext trust-root evidence is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_trust_root_evidence_no_delete BEFORE DELETE ON vNext_trust_root_evidence BEGIN SELECT RAISE(ABORT,'vNext trust-root evidence is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_recent_reauthentication_events_session_state_match BEFORE INSERT ON vNext_recent_reauthentication_events BEGIN SELECT CASE WHEN COALESCE((SELECT session_kind FROM vNext_sessions WHERE session_id=NEW.session_id AND authority_id=NEW.authority_id),'')!='online' THEN RAISE(ABORT,'VNEXT_REAUTH_ONLINE_SESSION_REQUIRED') WHEN NOT EXISTS(SELECT 1 FROM vNext_sessions s WHERE s.session_id=NEW.session_id AND s.authority_id=NEW.authority_id AND s.session_kind='online' AND s.status='active' AND julianday(NEW.verified_at)>=julianday(s.issued_at) AND julianday(NEW.verified_at)<julianday(s.expires_at) AND julianday(NEW.expires_at)<=julianday(s.expires_at) AND NEW.account_auth_version=s.account_auth_version AND NEW.account_access_version=s.account_access_version AND NEW.account_revocation_version=s.account_revocation_version AND NEW.device_credential_version=s.device_credential_version AND NEW.device_risk_version=s.device_risk_version AND NEW.installation_credential_version=s.installation_credential_version AND NEW.link_auth_version=s.link_auth_version AND NEW.link_access_version=s.link_access_version AND NEW.link_row_version=s.link_row_version) THEN RAISE(ABORT,'VNEXT_REAUTH_SESSION_STATE_INVALID') WHEN NOT EXISTS(SELECT 1 FROM vNext_sessions s JOIN vNext_authorities au ON au.authority_id=s.authority_id JOIN vNext_accounts a ON a.authority_id=s.authority_id AND a.account_id=s.account_id JOIN vNext_trusted_devices d ON d.authority_id=s.authority_id AND d.device_id=s.device_id JOIN vNext_device_installations i ON i.authority_id=s.authority_id AND i.device_id=s.device_id AND i.installation_id=s.installation_id JOIN vNext_account_device_links l ON l.authority_id=s.authority_id AND l.account_id=s.account_id AND l.device_id=s.device_id AND l.installation_id=s.installation_id AND l.link_id=s.link_id WHERE s.session_id=NEW.session_id AND s.authority_id=NEW.authority_id AND au.status='active' AND a.status='active' AND d.status='active' AND i.status='active' AND l.status='active' AND s.account_auth_version=a.auth_version AND s.account_access_version=a.access_version AND s.account_revocation_version=a.revocation_version AND s.device_credential_version=d.credential_version AND s.device_risk_version=d.risk_version AND s.installation_credential_version=i.credential_version AND s.link_auth_version=l.auth_version AND s.link_access_version=l.access_version AND s.link_row_version=l.row_version) THEN RAISE(ABORT,'VNEXT_REAUTH_CURRENT_PARENT_INVALID') END; END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_sessions_parent_state_match BEFORE INSERT ON vNext_sessions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM vNext_authorities au JOIN vNext_accounts a ON a.authority_id=au.authority_id JOIN vNext_trusted_devices d ON d.authority_id=au.authority_id JOIN vNext_device_installations i ON i.authority_id=au.authority_id AND i.device_id=d.device_id JOIN vNext_account_device_links l ON l.authority_id=au.authority_id AND l.account_id=a.account_id AND l.device_id=d.device_id AND l.installation_id=i.installation_id WHERE au.authority_id=NEW.authority_id AND au.status='active' AND a.account_id=NEW.account_id AND a.status='active' AND d.device_id=NEW.device_id AND d.status='active' AND i.installation_id=NEW.installation_id AND i.status='active' AND l.link_id=NEW.link_id AND l.status='active' AND NEW.account_auth_version=a.auth_version AND NEW.account_access_version=a.access_version AND NEW.account_revocation_version=a.revocation_version AND NEW.device_credential_version=d.credential_version AND NEW.device_risk_version=d.risk_version AND NEW.installation_credential_version=i.credential_version AND NEW.link_auth_version=l.auth_version AND NEW.link_access_version=l.access_version AND NEW.link_row_version=l.row_version) THEN RAISE(ABORT,'VNEXT_SESSION_PARENT_STATE_INVALID') END; END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_sessions_identity_immutable BEFORE UPDATE ON vNext_sessions WHEN NEW.session_id!=OLD.session_id OR NEW.authority_id!=OLD.authority_id OR NEW.account_id!=OLD.account_id OR NEW.device_id!=OLD.device_id OR NEW.installation_id!=OLD.installation_id OR NEW.link_id!=OLD.link_id OR NEW.session_kind!=OLD.session_kind OR NEW.issued_at!=OLD.issued_at OR NEW.expires_at!=OLD.expires_at OR NEW.account_auth_version!=OLD.account_auth_version OR NEW.account_access_version!=OLD.account_access_version OR NEW.account_revocation_version!=OLD.account_revocation_version OR NEW.device_credential_version!=OLD.device_credential_version OR NEW.device_risk_version!=OLD.device_risk_version OR NEW.installation_credential_version!=OLD.installation_credential_version OR NEW.link_auth_version!=OLD.link_auth_version OR NEW.link_access_version!=OLD.link_access_version OR NEW.link_row_version!=OLD.link_row_version OR NEW.created_at!=OLD.created_at BEGIN SELECT RAISE(ABORT,'vNext session identity is immutable'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_sessions_lifecycle_monotonic BEFORE UPDATE ON vNext_sessions WHEN NEW.status!=OLD.status OR NEW.revoked_at IS NOT OLD.revoked_at OR NEW.row_version!=OLD.row_version OR NEW.updated_at!=OLD.updated_at BEGIN SELECT CASE WHEN OLD.status!='active' OR NEW.status NOT IN ('revoked','expired') OR NEW.row_version!=OLD.row_version+1 OR julianday(NEW.updated_at)<=julianday(OLD.updated_at) OR (NEW.status='revoked' AND NEW.revoked_at IS NULL) OR (NEW.status='expired' AND NEW.revoked_at IS NOT NULL) THEN RAISE(ABORT,'vNext session lifecycle is immutable') END; END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_sessions_no_delete BEFORE DELETE ON vNext_sessions BEGIN SELECT RAISE(ABORT,'vNext session is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_recent_reauthentication_events_no_update BEFORE UPDATE ON vNext_recent_reauthentication_events BEGIN SELECT RAISE(ABORT,'vNext reauth event is append-only'); END`,
  `CREATE TRIGGER IF NOT EXISTS vNext_recent_reauthentication_events_no_delete BEFORE DELETE ON vNext_recent_reauthentication_events BEGIN SELECT RAISE(ABORT,'vNext reauth event is append-only'); END`,
]);

function normalizeSql(sql) { return String(sql).replace(/\s+/g, ' ').trim(); }
const REQUIRED_TABLE_SQL = Object.freeze(Object.fromEntries(
  STATEMENTS.filter(statement => statement.startsWith('CREATE TABLE')).map(statement => {
    const tableName = /^CREATE TABLE IF NOT EXISTS ([A-Za-z0-9_]+)/.exec(statement)[1];
    return [tableName, normalizeSql(statement.replace('CREATE TABLE IF NOT EXISTS ', 'CREATE TABLE '))];
  }),
));

const REQUIRED_COLUMNS = Object.freeze({
  vNext_account_device_links: ['link_id','authority_id','account_id','device_id','installation_id','status','auth_version','access_version','row_version','created_at','updated_at','revoked_at'],
  vNext_authorities: ['authority_id','status','created_at','updated_at'],
  vNext_accounts: ['account_id','authority_id','status','auth_version','access_version','revocation_version','row_version','created_at','updated_at'],
  vNext_capability_catalog: ['capability_id','status','surface_mask','created_at'],
  vNext_capability_overrides: ['override_id','authority_id','account_id','capability_id','effect','status','starts_at','ends_at','row_version','created_at','updated_at','revoked_at'],
  vNext_data_scope_grants: ['scope_grant_id','authority_id','account_id','scope_type','scope_value_hash','effect','status','starts_at','ends_at','row_version','created_at','updated_at','revoked_at'],
  vNext_device_installations: ['installation_id','authority_id','device_id','installation_public_key','key_fingerprint','status','credential_version','row_version','created_at','updated_at','revoked_at'],
  vNext_profile_bindings: ['binding_id','authority_id','account_id','profile_type','profile_id','status','evidence_hash','row_version','created_at','updated_at','revoked_at'],
  vNext_recent_reauthentication_events: ['reauth_event_id','authority_id','session_id','factor_class','evidence_sha256','account_auth_version','account_access_version','account_revocation_version','device_credential_version','device_risk_version','installation_credential_version','link_auth_version','link_access_version','link_row_version','verified_at','expires_at','created_at'],
  vNext_role_grants: ['grant_id','authority_id','account_id','role','status','grant_version','row_version','starts_at','ends_at','revoked_at','granted_by_account_id','created_at','updated_at'],
  vNext_schema_meta: ['schema_key','schema_version','applied_at'],
  vNext_sessions: ['session_id','authority_id','account_id','device_id','installation_id','link_id','session_kind','status','issued_at','expires_at','revoked_at','account_auth_version','account_access_version','account_revocation_version','device_credential_version','device_risk_version','installation_credential_version','link_auth_version','link_access_version','link_row_version','row_version','created_at','updated_at'],
  vNext_bootstrap_consumptions: ['marker_key','bootstrap_intent_id','authority_id','installation_key_fingerprint','policy_manifest_sha256','receipt_id','consumed_at'],
  vNext_trust_root_evidence: ['evidence_id','authority_id','receipt_id','actor_kind','event_id','assertion_evidence_sha256','backup_id','backup_manifest_sha256','created_at'],
  vNext_trusted_devices: ['device_id','authority_id','status','hardware_evidence_hash','risk_code','credential_version','risk_version','row_version','created_at','updated_at','revoked_at'],
  vNext_verified_contacts: ['contact_id','authority_id','account_id','contact_type','normalized_value_hash','verification_state','verification_evidence_hash','verified_at','revoked_at','row_version','created_at','updated_at'],
  vNext_authorization_audit_events: ['event_id','authority_id','receipt_id','reason_code','context_sha256','created_at'],
  vNext_authorization_command_receipts: ['receipt_id','authority_id','actor_key','actor_account_id','idempotency_key','command_type','target_kind','target_id','canonical_request_sha256','expected_row_version','outcome','result_code','canonical_result_json','canonical_result_sha256','committed_auth_version','committed_access_version','committed_revocation_version','committed_target_row_version','created_at'],
  vNext_authorization_outbox_events: ['event_id','authority_id','receipt_id','event_type','aggregate_kind','aggregate_id','aggregate_version','canonical_payload_json','payload_sha256','occurred_at'],
  vNext_authorization_policy_publications: ['publication_id','authority_id','receipt_id','policy_revision','policy_contract_version','canonical_manifest_json','policy_manifest_sha256','published_at'],
});
const REQUIRED_INDEX_SQL = Object.freeze({
  vNext_capability_overrides_one_active_capability: "CREATE UNIQUE INDEX vNext_capability_overrides_one_active_capability ON vNext_capability_overrides(authority_id,account_id,capability_id) WHERE status='active'",
  vNext_data_scope_grants_one_active_scope: "CREATE UNIQUE INDEX vNext_data_scope_grants_one_active_scope ON vNext_data_scope_grants(authority_id,account_id,scope_type,scope_value_hash) WHERE status='active'",
  vNext_profile_bindings_one_active_account_type: "CREATE UNIQUE INDEX vNext_profile_bindings_one_active_account_type ON vNext_profile_bindings(authority_id,account_id,profile_type) WHERE status='active'",
  vNext_profile_bindings_one_active_profile: "CREATE UNIQUE INDEX vNext_profile_bindings_one_active_profile ON vNext_profile_bindings(authority_id,profile_type,profile_id) WHERE status='active'",
  vNext_role_grants_one_active_role: "CREATE UNIQUE INDEX vNext_role_grants_one_active_role ON vNext_role_grants(authority_id,account_id,role) WHERE status='active'",
});
const REQUIRED_TRIGGER_SQL = Object.freeze({
  vNext_authorization_command_receipts_no_update: 'BEFORE UPDATE ON vNext_authorization_command_receipts BEGIN SELECT RAISE(ABORT,\'vNext command receipt is append-only\'); END',
  vNext_authorization_command_receipts_no_delete: 'BEFORE DELETE ON vNext_authorization_command_receipts BEGIN SELECT RAISE(ABORT,\'vNext command receipt is append-only\'); END',
  vNext_authorization_outbox_events_no_update: 'BEFORE UPDATE ON vNext_authorization_outbox_events BEGIN SELECT RAISE(ABORT,\'vNext outbox event is append-only\'); END',
  vNext_authorization_outbox_events_no_delete: 'BEFORE DELETE ON vNext_authorization_outbox_events BEGIN SELECT RAISE(ABORT,\'vNext outbox event is append-only\'); END',
  vNext_authorization_policy_publications_insert_guard: POLICY_PUBLICATION_INSERT_GUARD_SQL,
  vNext_authorization_policy_publications_no_update: 'BEFORE UPDATE ON vNext_authorization_policy_publications BEGIN SELECT RAISE(ABORT,\'vNext policy publication is append-only\'); END',
  vNext_authorization_policy_publications_no_delete: 'BEFORE DELETE ON vNext_authorization_policy_publications BEGIN SELECT RAISE(ABORT,\'vNext policy publication is append-only\'); END',
  vNext_authorization_audit_events_no_update: 'BEFORE UPDATE ON vNext_authorization_audit_events BEGIN SELECT RAISE(ABORT,\'vNext audit is append-only\'); END',
  vNext_authorization_audit_events_no_delete: 'BEFORE DELETE ON vNext_authorization_audit_events BEGIN SELECT RAISE(ABORT,\'vNext audit is append-only\'); END',
  vNext_bootstrap_consumptions_insert_guard: "BEFORE INSERT ON vNext_bootstrap_consumptions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM vNext_authorization_command_receipts r WHERE r.receipt_id=NEW.receipt_id AND r.authority_id=NEW.authority_id AND r.actor_key='bootstrap:'||NEW.bootstrap_intent_id AND r.actor_account_id IS NULL AND r.command_type='authority.bootstrap' AND r.target_kind='authority' AND r.target_id=NEW.authority_id AND r.outcome='accepted' AND r.result_code='AUTHORITY_BOOTSTRAPPED' AND r.expected_row_version=0 AND r.committed_target_row_version=1 AND r.committed_auth_version IS NULL AND r.committed_access_version IS NULL AND r.committed_revocation_version IS NULL AND julianday(NEW.consumed_at)>=julianday(r.created_at) AND json_type(r.canonical_result_json)='object' AND json_type(r.canonical_result_json,'$.authorityId')='text' AND json_type(r.canonical_result_json,'$.code')='text' AND json_type(r.canonical_result_json,'$.policyContractVersion')='integer' AND json_type(r.canonical_result_json,'$.policyManifestSha256')='text' AND json_type(r.canonical_result_json,'$.policyRevision')='integer' AND json_type(r.canonical_result_json,'$.publicationId')='text' AND json_type(r.canonical_result_json,'$.status')='text' AND json_extract(r.canonical_result_json,'$.authorityId')=NEW.authority_id AND json_extract(r.canonical_result_json,'$.code')='AUTHORITY_BOOTSTRAPPED' AND json_extract(r.canonical_result_json,'$.policyContractVersion')=1 AND json_extract(r.canonical_result_json,'$.policyManifestSha256')=NEW.policy_manifest_sha256 AND json_extract(r.canonical_result_json,'$.policyRevision')=1 AND json_extract(r.canonical_result_json,'$.status')='accepted' AND (SELECT COUNT(*) FROM json_each(r.canonical_result_json))=7) THEN RAISE(ABORT,'VNEXT_BOOTSTRAP_MARKER_RECEIPT_INVALID') END; END",
  vNext_bootstrap_consumptions_no_update: 'BEFORE UPDATE ON vNext_bootstrap_consumptions BEGIN SELECT RAISE(ABORT,\'vNext bootstrap consumption is append-only\'); END',
  vNext_bootstrap_consumptions_no_delete: 'BEFORE DELETE ON vNext_bootstrap_consumptions BEGIN SELECT RAISE(ABORT,\'vNext bootstrap consumption is append-only\'); END',
  vNext_trust_root_evidence_insert_guard: "BEFORE INSERT ON vNext_trust_root_evidence BEGIN SELECT CASE WHEN NEW.actor_kind='deployment_bootstrap' AND NOT EXISTS(SELECT 1 FROM vNext_bootstrap_consumptions m WHERE m.authority_id=NEW.authority_id AND m.bootstrap_intent_id=NEW.event_id AND m.receipt_id=NEW.receipt_id AND julianday(NEW.created_at)>=julianday(m.consumed_at)) THEN RAISE(ABORT,'VNEXT_TRUST_ROOT_EVIDENCE_RECEIPT_INVALID') WHEN NEW.actor_kind='owner_recovery_event' AND NOT EXISTS(SELECT 1 FROM vNext_authorization_command_receipts r WHERE r.receipt_id=NEW.receipt_id AND r.authority_id=NEW.authority_id AND r.actor_key='recovery:'||NEW.event_id AND r.actor_account_id IS NULL AND r.command_type='authority.owner_recover' AND r.target_kind='authority' AND r.target_id=NEW.authority_id AND r.outcome='accepted' AND r.result_code='OWNER_RECOVERY_COMPLETED' AND r.expected_row_version IS NULL AND r.committed_target_row_version IS NULL AND r.committed_auth_version IS NULL AND r.committed_access_version IS NULL AND r.committed_revocation_version IS NULL AND julianday(NEW.created_at)>=julianday(r.created_at) AND json_type(r.canonical_result_json)='object' AND json_type(r.canonical_result_json,'$.authorityId')='text' AND json_type(r.canonical_result_json,'$.code')='text' AND json_type(r.canonical_result_json,'$.replacementAccountId')='text' AND json_type(r.canonical_result_json,'$.status')='text' AND json_extract(r.canonical_result_json,'$.authorityId')=NEW.authority_id AND json_extract(r.canonical_result_json,'$.code')='OWNER_RECOVERY_COMPLETED' AND json_extract(r.canonical_result_json,'$.status')='accepted' AND (SELECT COUNT(*) FROM json_each(r.canonical_result_json))=4) THEN RAISE(ABORT,'VNEXT_TRUST_ROOT_EVIDENCE_RECEIPT_INVALID') END; END",
  vNext_trust_root_evidence_no_update: 'BEFORE UPDATE ON vNext_trust_root_evidence BEGIN SELECT RAISE(ABORT,\'vNext trust-root evidence is append-only\'); END',
  vNext_trust_root_evidence_no_delete: 'BEFORE DELETE ON vNext_trust_root_evidence BEGIN SELECT RAISE(ABORT,\'vNext trust-root evidence is append-only\'); END',
  vNext_recent_reauthentication_events_session_state_match: "BEFORE INSERT ON vNext_recent_reauthentication_events BEGIN SELECT CASE WHEN COALESCE((SELECT session_kind FROM vNext_sessions WHERE session_id=NEW.session_id AND authority_id=NEW.authority_id),'')!='online' THEN RAISE(ABORT,'VNEXT_REAUTH_ONLINE_SESSION_REQUIRED') WHEN NOT EXISTS(SELECT 1 FROM vNext_sessions s WHERE s.session_id=NEW.session_id AND s.authority_id=NEW.authority_id AND s.session_kind='online' AND s.status='active' AND julianday(NEW.verified_at)>=julianday(s.issued_at) AND julianday(NEW.verified_at)<julianday(s.expires_at) AND julianday(NEW.expires_at)<=julianday(s.expires_at) AND NEW.account_auth_version=s.account_auth_version AND NEW.account_access_version=s.account_access_version AND NEW.account_revocation_version=s.account_revocation_version AND NEW.device_credential_version=s.device_credential_version AND NEW.device_risk_version=s.device_risk_version AND NEW.installation_credential_version=s.installation_credential_version AND NEW.link_auth_version=s.link_auth_version AND NEW.link_access_version=s.link_access_version AND NEW.link_row_version=s.link_row_version) THEN RAISE(ABORT,'VNEXT_REAUTH_SESSION_STATE_INVALID') WHEN NOT EXISTS(SELECT 1 FROM vNext_sessions s JOIN vNext_authorities au ON au.authority_id=s.authority_id JOIN vNext_accounts a ON a.authority_id=s.authority_id AND a.account_id=s.account_id JOIN vNext_trusted_devices d ON d.authority_id=s.authority_id AND d.device_id=s.device_id JOIN vNext_device_installations i ON i.authority_id=s.authority_id AND i.device_id=s.device_id AND i.installation_id=s.installation_id JOIN vNext_account_device_links l ON l.authority_id=s.authority_id AND l.account_id=s.account_id AND l.device_id=s.device_id AND l.installation_id=s.installation_id AND l.link_id=s.link_id WHERE s.session_id=NEW.session_id AND s.authority_id=NEW.authority_id AND au.status='active' AND a.status='active' AND d.status='active' AND i.status='active' AND l.status='active' AND s.account_auth_version=a.auth_version AND s.account_access_version=a.access_version AND s.account_revocation_version=a.revocation_version AND s.device_credential_version=d.credential_version AND s.device_risk_version=d.risk_version AND s.installation_credential_version=i.credential_version AND s.link_auth_version=l.auth_version AND s.link_access_version=l.access_version AND s.link_row_version=l.row_version) THEN RAISE(ABORT,'VNEXT_REAUTH_CURRENT_PARENT_INVALID') END; END",
  vNext_sessions_parent_state_match: "BEFORE INSERT ON vNext_sessions BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM vNext_authorities au JOIN vNext_accounts a ON a.authority_id=au.authority_id JOIN vNext_trusted_devices d ON d.authority_id=au.authority_id JOIN vNext_device_installations i ON i.authority_id=au.authority_id AND i.device_id=d.device_id JOIN vNext_account_device_links l ON l.authority_id=au.authority_id AND l.account_id=a.account_id AND l.device_id=d.device_id AND l.installation_id=i.installation_id WHERE au.authority_id=NEW.authority_id AND au.status='active' AND a.account_id=NEW.account_id AND a.status='active' AND d.device_id=NEW.device_id AND d.status='active' AND i.installation_id=NEW.installation_id AND i.status='active' AND l.link_id=NEW.link_id AND l.status='active' AND NEW.account_auth_version=a.auth_version AND NEW.account_access_version=a.access_version AND NEW.account_revocation_version=a.revocation_version AND NEW.device_credential_version=d.credential_version AND NEW.device_risk_version=d.risk_version AND NEW.installation_credential_version=i.credential_version AND NEW.link_auth_version=l.auth_version AND NEW.link_access_version=l.access_version AND NEW.link_row_version=l.row_version) THEN RAISE(ABORT,'VNEXT_SESSION_PARENT_STATE_INVALID') END; END",
  vNext_sessions_identity_immutable: "BEFORE UPDATE ON vNext_sessions WHEN NEW.session_id!=OLD.session_id OR NEW.authority_id!=OLD.authority_id OR NEW.account_id!=OLD.account_id OR NEW.device_id!=OLD.device_id OR NEW.installation_id!=OLD.installation_id OR NEW.link_id!=OLD.link_id OR NEW.session_kind!=OLD.session_kind OR NEW.issued_at!=OLD.issued_at OR NEW.expires_at!=OLD.expires_at OR NEW.account_auth_version!=OLD.account_auth_version OR NEW.account_access_version!=OLD.account_access_version OR NEW.account_revocation_version!=OLD.account_revocation_version OR NEW.device_credential_version!=OLD.device_credential_version OR NEW.device_risk_version!=OLD.device_risk_version OR NEW.installation_credential_version!=OLD.installation_credential_version OR NEW.link_auth_version!=OLD.link_auth_version OR NEW.link_access_version!=OLD.link_access_version OR NEW.link_row_version!=OLD.link_row_version OR NEW.created_at!=OLD.created_at BEGIN SELECT RAISE(ABORT,'vNext session identity is immutable'); END",
  vNext_sessions_lifecycle_monotonic: "BEFORE UPDATE ON vNext_sessions WHEN NEW.status!=OLD.status OR NEW.revoked_at IS NOT OLD.revoked_at OR NEW.row_version!=OLD.row_version OR NEW.updated_at!=OLD.updated_at BEGIN SELECT CASE WHEN OLD.status!='active' OR NEW.status NOT IN ('revoked','expired') OR NEW.row_version!=OLD.row_version+1 OR julianday(NEW.updated_at)<=julianday(OLD.updated_at) OR (NEW.status='revoked' AND NEW.revoked_at IS NULL) OR (NEW.status='expired' AND NEW.revoked_at IS NOT NULL) THEN RAISE(ABORT,'vNext session lifecycle is immutable') END; END",
  vNext_sessions_no_delete: "BEFORE DELETE ON vNext_sessions BEGIN SELECT RAISE(ABORT,'vNext session is append-only'); END",
  vNext_recent_reauthentication_events_no_update: 'BEFORE UPDATE ON vNext_recent_reauthentication_events BEGIN SELECT RAISE(ABORT,\'vNext reauth event is append-only\'); END',
  vNext_recent_reauthentication_events_no_delete: 'BEFORE DELETE ON vNext_recent_reauthentication_events BEGIN SELECT RAISE(ABORT,\'vNext reauth event is append-only\'); END',
});

function kernelError(code) { return Object.assign(new Error(code), { code }); }
function assertConnectionShape(db) {
  if (!db || typeof db.exec !== 'function' || typeof db.prepare !== 'function' || typeof db.transaction !== 'function' || typeof db.pragma !== 'function') throw kernelError('VNEXT_REFERENCE_SQLITE_CONNECTION_REQUIRED');
}
function enableAndAssertForeignKeys(db) {
  assertConnectionShape(db);
  db.pragma('foreign_keys = ON');
  if (Number(db.pragma('foreign_keys', { simple: true })) !== 1) throw kernelError('VNEXT_REFERENCE_FOREIGN_KEYS_REQUIRED');
}
function assertSchema(db) {
  const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'vNext_%' ORDER BY name").all().map(row => row.name);
  if (JSON.stringify(tables) !== JSON.stringify(V_NEXT_CONTROL_PLANE_REFERENCE_TABLES)) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
  for (const [table, expected] of Object.entries(REQUIRED_COLUMNS)) {
    const actual = db.prepare(`PRAGMA table_info(${table})`).all().map(row => row.name);
    if (JSON.stringify(actual) !== JSON.stringify(expected)) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
  }
  const tableSql = db.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name LIKE 'vNext_%'").all();
  if (tableSql.some(table => normalizeSql(table.sql) !== REQUIRED_TABLE_SQL[table.name])) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
  const indexes = db.prepare("SELECT name,sql,tbl_name FROM sqlite_master WHERE type='index' AND sql IS NOT NULL AND (name LIKE 'vNext_%' OR tbl_name LIKE 'vNext_%')").all();
  if (indexes.length !== Object.keys(REQUIRED_INDEX_SQL).length || indexes.some(index => normalizeSql(index.sql) !== REQUIRED_INDEX_SQL[index.name])) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
  const triggers = db.prepare("SELECT name,sql,tbl_name FROM sqlite_master WHERE type='trigger' AND (name LIKE 'vNext_%' OR tbl_name LIKE 'vNext_%')").all();
  if (triggers.length !== Object.keys(REQUIRED_TRIGGER_SQL).length || triggers.some(trigger => normalizeSql(trigger.sql) !== `CREATE TRIGGER ${trigger.name} ${REQUIRED_TRIGGER_SQL[trigger.name]}`)) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
}
function bootstrapVNextControlPlaneReference(db, { now = () => new Date().toISOString(), testHooks = {} } = {}) {
  enableAndAssertForeignKeys(db);
  const hasMetaTable = db.prepare("SELECT 1 AS present FROM sqlite_master WHERE type='table' AND name='vNext_schema_meta'").get();
  if (hasMetaTable) assertSchema(db);
  const apply = db.transaction(() => {
    for (let index = 0; index < STATEMENTS.length; index += 1) { db.exec(STATEMENTS[index]); if (typeof testHooks.afterStatement === 'function') testHooks.afterStatement({ index: index + 1 }); }
    db.prepare(`INSERT INTO vNext_schema_meta(schema_key,schema_version,applied_at) VALUES('control-plane-reference',5,?) ON CONFLICT(schema_key) DO NOTHING`).run(String(now()));
    const meta = db.prepare("SELECT schema_version FROM vNext_schema_meta WHERE schema_key='control-plane-reference'").get();
    if (!meta || Number(meta.schema_version) !== 5) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
    assertSchema(db);
  });
  apply();
  return Object.freeze({ schemaVersion: 5, tables: V_NEXT_CONTROL_PLANE_REFERENCE_TABLES });
}
module.exports = {
  V_NEXT_CONTROL_PLANE_REFERENCE_TABLES,
  assertVNextControlPlaneReferenceSchema(db) {
    assertConnectionShape(db);
    if (Number(db.pragma('foreign_keys', { simple: true })) !== 1) throw kernelError('VNEXT_REFERENCE_FOREIGN_KEYS_REQUIRED');
    const meta = db.prepare("SELECT schema_version FROM vNext_schema_meta WHERE schema_key='control-plane-reference'").get();
    if (!meta || Number(meta.schema_version) !== 5) throw kernelError('VNEXT_REFERENCE_SCHEMA_DRIFT');
    assertSchema(db);
  },
  bootstrapVNextControlPlaneReference,
};
