const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = relativePath => fs.readFileSync(path.join(root, relativePath), 'utf8');
const absent = relativePath => assert.ok(
  !fs.existsSync(path.join(root, relativePath)),
  `${relativePath} must not remain after the desktop identity architecture cutover`
);

const packageJson = read('package.json');
assert.ok(!packageJson.includes('singleUserPairingEnvelope'), 'desktop packages must not ship the retired pairing envelope');
assert.ok(!packageJson.includes('singleUserDesktopIdentityService'), 'test commands must not execute retired identity services');
assert.ok(!packageJson.includes('singleUserPairingClient'), 'test commands must not execute retired pairing clients');
const desktopIdentityVault = read('public/desktopIdentityVault.js');
for (const retiredHelper of [
  'signAuthorityHttpRequest',
  'createAuthorityCommand',
  'signAuthorityProjection',
]) {
  assert.ok(!desktopIdentityVault.includes(retiredHelper),
    `desktop identity vault must not retain retired local-authority helper ${retiredHelper}`);
}

[
  'backend/src/services/desktopSessionService.js',
  'backend/src/schema.sql',
  'scripts/audit-runtime-evidence.js',
  'scripts/check_deploy_readiness.js',
  'src/services/desktopIdentityClient.mjs',
  'src/pages/IdentityDeviceCenter.tsx',
  'public/electron.js',
  'src/custom.d.ts',
].forEach(relativePath => {
  const source = read(relativePath);
  assert.ok(!/single[_-]?user|singleUser/i.test(source), `${relativePath} must use only the managed identity architecture`);
});
assert.ok(!read('backend/src/schema.sql').includes('desktop_single_user_pairing_'),
  'new databases must not create retired pairing tables');

absent('gateway/src/routes/cloudRelay.js');

[
  'backend/src/services/singleUserDesktopIdentityService.js',
  'backend/src/services/singleUserDesktopIdentityService.test.js',
  'backend/src/services/singleUserPairingEnvelope.js',
  'public/singleUserPairingEnvelope.js',
  'public/singleUserPairingEnvelope.test.js',
  'src/services/singleUserPairingClient.mjs',
  'src/services/singleUserPairingClient.test.js',
  'scripts/inspect-single-user-pairing-state.js',
  'scripts/live-cloud-pairing-route-smoke.js',
  'scripts/single-user-pairing-runtime-smoke.js',
  'scripts/deploy_ws_token_fix.py',
  'scripts/check_backend.py',
  'scripts/check_gw_status.py',
  'scripts/check_network.py',
  'scripts/check_processes.py',
  'scripts/check_server.py',
  'scripts/check_tokens.py',
  'scripts/deploy_server_fix.py',
  'scripts/deploy_ws_fix.py',
  'scripts/final_verify.py',
  'scripts/fix_backend_import.py',
  'backend/src/services/desktopSessionRelayService.js',
  'src/services/desktopSessionRelayClient.mjs',
  'src/services/websocketClient.mjs',
  'src/services/websocketClient.test.js',
  'scripts/packaged-host-identity-ui.test.js',
  'scripts/real-two-desktop-e2e.js',
  'public/desktopIdentityKind.js',
  'public/desktopCredentialStore.js',
  'public/primaryHostCredentialStore.js',
  'public/primaryHostOperationValidation.js',
  'public/primaryHostRuntimeManager.js',
  'public/primaryHostRuntimeStatus.js',
  'public/primaryHostRelaunchReadiness.js',
  'public/primaryHostLocalProjectionReader.js',
  'public/primaryHostLocalDraftExecutor.js',
  'public/primaryHostListenPolicy.js',
  'public/windowsHostFirewall.js',
  'src/services/authorityWebSocketTransport.mjs',
  'src/services/authorityWebSocketTransport.test.js',
  'src/services/authorityTransports.mjs',
  'src/services/authorityTransports.test.js',
  'backend/src/services/authorityCloudRuntime.js',
  'backend/src/services/authorityCloudRuntime.test.js',
  'backend/src/websocket/authorityRelayRouter.js',
  'backend/src/websocket/authoritySocketServer.js',
  'backend/src/websocket/authoritySocketServer.test.js',
  'backend/src/websocket/client.js',
  'backend/src/websocket/client.test.js',
  'backend/src/websocket/cloudRelayAuthorityServer.test.js',
  'backend/src/websocket/cloudRelayServer.js',
  'backend/src/websocket/hostTaskWakeup.js',
  'backend/src/websocket/hostTaskWakeup.test.js',
  'backend/src/websocket/websocketAuthorityOwnership.test.js',
  'backend/src/routes/authorityProtocol.js',
  'backend/src/routes/authorityProtocol.http.test.js',
  'backend/src/routes/miniappAuthorityApplications.js',
  'backend/src/routes/miniappAuthorityApplications.http.test.js',
  'backend/src/routes/miniappAuthorityProjection.js',
  'backend/src/routes/miniappAuthorityProjection.test.js',
  'backend/src/routes/cloudRelay.js',
  'backend/src/routes/cloudRelay.http.test.js',
  'backend/src/routes/desktopCloudSync.test.js',
  'backend/src/routes/miniappApplications.js',
  'backend/src/routes/miniappApplications.http.test.js',
  'backend/src/routes/miniappCloudRoutes.test.js',
  'backend/src/routes/miniappFirewall.test.js',
  'backend/src/services/cloudRelayActorGrant.js',
  'backend/src/services/cloudRelayActorGrant.test.js',
  'backend/src/services/cloudRelayClient.js',
  'backend/src/services/cloudRelayClient.test.js',
  'backend/src/services/cloudRelayTaskService.js',
  'backend/src/services/cloudRelayTaskSchemaMigration.test.js',
  'backend/src/services/relayAssertionService.js',
  'backend/src/services/relayAssertionService.test.js',
  'backend/src/services/questionPreviewIndex.js',
  'backend/src/services/questionPreviewIndex.test.js',
  'backend/src/services/legacyArchitectureGate.js',
  'backend/src/services/legacyArchitectureGate.test.js',
  'backend/src/services/miniappApplicationService.js',
  'backend/src/services/miniappApplicationService.test.js',
  'backend/src/services/miniappApplicationReviewService.js',
  'backend/src/services/miniappApplicationReviewService.test.js',
  'backend/src/services/miniappProvisioningReconciler.js',
  'backend/src/services/miniappProvisioningReconciler.test.js',
  'backend/src/services/identityProvisioningService.js',
  'backend/src/services/identityProvisioningService.test.js',
  'backend/src/services/primaryHostIdentityService.js',
  'backend/src/services/primaryHostIdentityService.test.js',
  'backend/src/services/primaryHostLocalValidationService.js',
  'backend/src/services/primaryHostLocalValidationService.test.js',
  'backend/src/services/primaryHostPreflightProofService.js',
  'backend/src/services/primaryHostPreflightProofService.test.js',
  'backend/src/services/primaryHostReceiptProtocol.js',
  'backend/src/services/primaryHostReceiptProtocol.test.js',
  'backend/src/services/primaryHostRecoveryDeliveryProtocol.js',
  'backend/src/services/primaryHostRecoveryDeliveryProtocol.test.js',
  'backend/src/services/primaryHostRecoveryDeliveryService.js',
  'backend/src/services/primaryHostRecoveryDeliveryService.test.js',
  'backend/src/services/primaryHostSyncPreflightService.js',
  'backend/src/services/primaryHostSyncPreflightService.test.js',
  'backend/src/services/hostRecoveryFactorService.js',
  'backend/src/services/hostRecoveryFactorService.test.js',
  'shared/cloudRelayLogic.js',
  'shared/primaryHostSigningKey.js',
  'scripts/check_cloud_relay.js',
  'scripts/check_cloud_relay.test.js',
  'scripts/hostIdentityUiProfile.js',
  'scripts/hostIdentityUiProfile.test.js',
  'src/components/HostAuthorityExecutionMonitor.tsx',
  'src/components/HostAuthorityExecutionMonitor.test.js',
  'src/pages/systemSettingsAuthoritySurface.test.js',
  'src/services/cloudRelayHostApi.ts',
  'src/services/cloudRelayHostApi.test.js',
  'src/services/authorityRoleReviewRuntime.mjs',
  'src/services/authorityRoleReviewRuntime.test.js',
  'src/services/authoritySyncSurfacePolicy.mjs',
  'src/services/authoritySyncSurfacePolicy.test.js',
  'backend/src/services/authorityAccessService.js',
  'backend/src/services/authorityAccessService.test.js',
  'backend/src/services/authorityBusinessMutationService.js',
  'backend/src/services/authorityBusinessMutationService.test.js',
  'backend/src/services/authorityCloudEpochService.js',
  'backend/src/services/authorityCloudEpochService.test.js',
  'backend/src/services/authorityCommandAuthorizationService.js',
  'backend/src/services/authorityCommandAuthorizationService.test.js',
  'backend/src/services/authorityCommandRegistry.js',
  'backend/src/services/authorityCommandRegistry.test.js',
  'backend/src/services/authorityCommandService.js',
  'backend/src/services/authorityCommandService.test.js',
  'backend/src/services/authorityCompositeCommandSource.js',
  'backend/src/services/authorityCompositeCommandSource.test.js',
  'backend/src/services/authorityDeviceControlCache.js',
  'backend/src/services/authorityDeviceControlCache.test.js',
  'backend/src/services/authorityDeviceRequestAuth.js',
  'backend/src/services/authorityMigrationService.js',
  'backend/src/services/authorityMigrationService.test.js',
  'backend/src/services/authorityProjectionService.js',
  'backend/src/services/authorityProjectionService.test.js',
  'backend/src/services/authorityProjectionSourceService.js',
  'backend/src/services/authorityProjectionSourceService.test.js',
  'backend/src/services/authorityProjectionStoreService.js',
  'backend/src/services/authorityProjectionStoreService.test.js',
  'backend/src/services/authorityProjectionVersionService.js',
  'backend/src/services/authorityProjectionVersionService.test.js',
  'backend/src/services/authorityRoleMirrorService.js',
  'backend/src/services/authoritySocketCommandHandler.js',
  'backend/src/services/authoritySocketCommandHandler.test.js',
  'backend/src/services/miniappAuthorityCommandAdapterService.js',
  'backend/src/services/miniappAuthorityCommandAdapterService.test.js',
  'backend/src/services/authorityBusinessDatabase.test.js',
  'backend/src/services/authorityDatabaseMigration.test.js',
  'backend/src/services/authorityCommandInboxSchema.test.js',
  'scripts/runtime-architecture-rehearsal.js',
  'scripts/runtime-architecture-rehearsal.test.js',
  'shared/authorityHttpAuth.js',
  'shared/authorityHttpAuth.test.js',
  'shared/authorityProjectionProtocol.js',
  'shared/authorityProjectionProtocol.test.js',
].forEach(absent);

console.log('desktop architecture cutover checks passed');
