export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/login/privacy',
    'pages/desktop-authorization/index',
    'pages/index/index',
    'pages/forbidden/index',
    'pages/schedule/index',
    'pages/schedule/detail/index',
    'pages/schedule/edit/index',
    'pages/students/index',
    'pages/student-detail/index',
    'pages/courses/index',
    'pages/teachers/index',
    'pages/payments/index',
    'pages/stats/index',
    'pages/question-bank/index',
    'pages/assets/index',
    'pages/settings/index',
    'pages/admin/users/index',
    'pages/unrecognized-experience/index',
    'pages/unrecognized-apply/index',
    'pages/unrecognized-status/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#1f6f68',
    navigationBarTitleText: '教育综合服务平台',
    navigationBarTextStyle: 'white',
    backgroundColor: '#f7f4ee',
  },
  tabBar: {
    custom: true,
    color: '#8b96a8',
    selectedColor: '#1f6f68',
    backgroundColor: '#fffdf8',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/schedule/index',
        text: '课程表',
        iconPath: 'assets/tabbar/schedule.png',
        selectedIconPath: 'assets/tabbar/schedule-active.png',
      },
      {
        pagePath: 'pages/students/index',
        text: '学员',
        iconPath: 'assets/tabbar/students.png',
        selectedIconPath: 'assets/tabbar/students-active.png',
      },
      {
        pagePath: 'pages/assets/index',
        text: '财务',
        iconPath: 'assets/tabbar/assets.png',
        selectedIconPath: 'assets/tabbar/assets-active.png',
      },
      {
        pagePath: 'pages/settings/index',
        text: '设置',
        iconPath: 'assets/tabbar/settings.png',
        selectedIconPath: 'assets/tabbar/settings-active.png',
      },
    ],
  },
});
