'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const display = source => source.replace(/\\u([0-9a-fA-F]{4})/g, (_match, hex) => String.fromCharCode(Number.parseInt(hex, 16)));
const source = display(fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8'));
const paperSource = display(fs.readFileSync(path.join(__dirname, '..', 'question-paper', 'index.tsx'), 'utf8'));
const overlaySource = display(fs.readFileSync(path.join(__dirname, '..', '..', 'components', 'QuestionBasketOverlay.tsx'), 'utf8'));
const apiSource = display(fs.readFileSync(path.join(__dirname, '..', '..', 'utils', 'api.ts'), 'utf8'));

assert.match(source, /miniappCloudBusinessApi\.listQuestionPreviews/, 'question previews must read from the cloud authority');
assert.match(source, /createQuestionDisplay\(question\)/, 'question cards must project the structured cloud document through the shared display contract');
assert.match(source, /display\.answer/, 'limited question browsing must render the projected cloud answer');
assert.match(source, /display\.explanation/, 'limited question browsing must render the projected cloud explanation');
const assetSelectionBlock = source.match(/function questionAssetRequests\(question: QuestionPreview\)[\s\S]*?\n\}/);
assert.ok(assetSelectionBlock, 'question media selection must remain an explicit, testable boundary');
assert.match(assetSelectionBlock[0], /createQuestionDisplay\(question\)/, 'media selection must inspect exactly the content projected for display');
assert.match(assetSelectionBlock[0], /questionAssetKeys\(display\)/, 'media selection must include structured stem, options, subquestions, answer and explanation assets');
assert.doesNotMatch(assetSelectionBlock[0], /question\.(?:stemPreview|options|answer|explanation|richContent)/, 'media selection must not diverge from the shared display projection');
assert.match(source, /expandedQuestionId/, 'limited question browsing must reuse the desktop-style answer drawer state');
assert.match(source, /expandedQuestionId === question\.id/, 'only a selected question may reveal its answer and explanation');
assert.match(source, /expanded && hasAnswerContent \? <View className='question-preview-answer'>/, 'answers must be conditional on the selected question drawer and real answer content');
const expandedAnswerBlock = source.match(/expanded && hasAnswerContent \? <View className='question-preview-answer'>([\s\S]*?)<\/View> : null/);
assert.ok(expandedAnswerBlock, 'expanded answer rendering must remain an explicit, testable boundary');
assert.match(source, /miniRichNodes\(display\.answer \|\| [^,]+, assetPaths\)/, 'expanded answers must render resolved rich-media paths');
assert.match(source, /miniRichNodes\(display\.explanation, assetPaths\)/, 'expanded explanations must render resolved rich-media paths');
assert.match(expandedAnswerBlock[1], /display\.subQuestions\.some\(subQuestion => subQuestion\.answer\)/, 'expanded structured questions must reveal their per-subquestion answers');
assert.match(expandedAnswerBlock[1], /miniRichNodes\(subQuestion\.answer, assetPaths\)/, 'per-subquestion answers must use the same rich-media resolver as the main answer');
assert.match(source, /const VISITOR_QUESTION_LIMIT = 20/, 'visitor question browsing must have an enforced display boundary');
assert.match(source, /const visibleQuestions = isVisitor \? matchingQuestions\.slice\(0, VISITOR_QUESTION_LIMIT\) : matchingQuestions/, 'visitor browsing must render only the bounded slice rather than every cloud question');
assert.match(source, /const canContinue = response\.data\?\.hasMore === true/, 'the page must retain the cloud look-ahead flag without exposing another question');
assert.match(source, /if \(isVisitor\) \{[\s\S]*?if \(hasMoreQuestions\) requestMoreQuestionAccess\(\)/, 'the visitor boundary prompt must appear only after the user tries to browse past the loaded list');
assert.doesNotMatch(source, /className='question-more-entry'/, 'the visitor limit must not be announced as permanent page chrome');
assert.match(source, /question\.source/, 'question cards must show the cloud-provided source label');
assert.match(source, /question\.knowledgeLabels/, 'question cards must show cloud-resolved knowledge labels');
assert.match(source, /requestQuestionAssetDelivery/, 'question cards must fetch NAS-backed media only through the cloud delivery boundary');
const listLoadBlock = source.match(/const loadQuestionPage = async \(append: boolean, cursor: string \| null\) => \{([\s\S]*?)\n  \};\s+const loadQuestions/);
assert.ok(listLoadBlock, 'question list loading must remain an explicit, testable boundary');
assert.doesNotMatch(listLoadBlock[1], /requestQuestionAssetDelivery/, 'loading the question list must not prepare every rich-media delivery');
assert.match(source, /const loadQuestionAssets = async \(question: QuestionPreview\)/, 'one question must prepare its rich media only on demand');
const onDemandAssetBlock = source.match(/const loadQuestionAssets = async \(question: QuestionPreview\) => \{([\s\S]*?)\n  \};\s+const prefetchQuestionAssets/);
assert.ok(onDemandAssetBlock, 'on-demand question media loading must remain an explicit, testable boundary');
assert.strictEqual((onDemandAssetBlock[1].match(/requestQuestionAssetDelivery/g) || []).length, 1, 'one on-demand asset may create at most one delivery per attempt');
assert.match(onDemandAssetBlock[1], /readQuestionAssetDelivery\(token, deliveryId\)/, 'queued media must poll the prepared delivery by the locked id');
assert.match(onDemandAssetBlock[1], /const deliveryId = delivery\.deliveryId/, 'question-bank delivery polling must lock the original delivery id');
assert.match(onDemandAssetBlock[1], /refreshed\.data\.delivery\.deliveryId !== deliveryId/, 'a changed delivery id must be rejected instead of followed');
assert.match(onDemandAssetBlock[1], /\['queued', 'leased'\]\.includes\(delivery\.status\)/, 'terminal delivery failures must not be polled repeatedly');
assert.match(onDemandAssetBlock[1], /downloadQuestionAssetDelivery\(token, deliveryId\)/, 'question-bank download must use the locked delivery id');
assert.match(source, /const QUESTION_ASSET_CONCURRENCY = 4/, 'question-bank media loading must keep a small device-safe concurrency ceiling');
assert.match(onDemandAssetBlock[1], /Math\.min\(QUESTION_ASSET_CONCURRENCY, requests\.length\)/, 'question-bank media workers must never exceed the concurrency ceiling');
assert.match(onDemandAssetBlock[1], /await Promise\.all\(workers\)/, 'only the bounded question-bank worker pool may run concurrently');
assert.doesNotMatch(onDemandAssetBlock[1], /Promise\.all\(requests\.map/, 'one rich question must not start every media request at once');
assert.match(source, /if \(expanding\) void loadQuestionAssets\(question\)/, 'expanding a question must be the deliberate trigger for its rich-media delivery');
assert.match(source, /const QUESTION_INITIAL_MEDIA_PREFETCH = \d+/, 'the first viewport must have a bounded rich-media prefetch budget');
assert.match(source, /visibleQuestions\.slice\(0, QUESTION_INITIAL_MEDIA_PREFETCH\)/, 'only the first visible questions may be proactively prepared on initial render');
assert.match(source, /prefetchQuestionAssets/, 'visible rich-media preparation must use an explicit bounded worker boundary');
assert.match(source, /resolveQuestionAssetRefs/, 'question RichText must visibly preserve unresolved media instead of replacing private references with an empty string');
assert.doesNotMatch(source, /paths\[assetKey\] \|\| ''/, 'unresolved question media must never silently disappear');
assert.match(source, /requestedQuestionAssetsRef\.current\.has\(requestKey\)/, 'overlapping expansion must not duplicate an in-flight delivery request');
assert.match(onDemandAssetBlock[1], /if \(!requestCompleted\) requestedQuestionAssetsRef\.current\.delete\(requestKey\)/, 'any failed media attempt must release its retry lock');
assert.match(source, /pageActiveRef = useRef\(true\)/, 'late question-bank responses must be rejected after page unmount');
assert.match(onDemandAssetBlock[1], /authSessionRuntime\.isSameSession\(session\)/, 'late media responses must be rejected after an account switch');
assert.match(listLoadBlock[1], /authSessionRuntime\.isSameSession\(session\)/, 'late question-list responses must be rejected after an account switch');
assert.doesNotMatch(source, /setTimeout\(\(\) => \{ void loadQuestions\(\); \}, 1500\)/, 'a failed asset delivery must not restart the whole question-list request cycle');
assert.match(source, /<RichText/, 'question cards must render resolved rich-media content instead of raw asset references');
assert.match(source, /questionBasketStore\.reconcileIdentity\(\)/, 'the first selection after a restored session must reconcile the live account scope');
assert.match(source, /questionBasketStore\.toggle\(questionId\)/, 'question selection must update the singleton account-scoped basket');
assert.match(apiSource, /listQuestionPreviews\(token: string, options:/, 'the miniapp cloud client must accept bounded cursor-page options');
assert.match(apiSource, /limit: options\.limit/, 'the question preview request must send the page size to cloud');
assert.match(apiSource, /cursor: options\.cursor/, 'the question preview request must send the opaque cloud cursor without decoding it locally');
for (const field of ['subject', 'query', 'source', 'knowledgePoint', 'type', 'difficulty', 'grade', 'semester', 'examType', 'examYear']) {
  assert.match(apiSource, new RegExp(`${field}: options\\.${field}`), `the question preview request must send ${field} to cloud`);
  assert.match(listLoadBlock[1], new RegExp(`${field}:`), `the question page must keep ${field} inside the cloud request boundary`);
}
for (const key of ['grades', 'semesters', 'examTypes', 'examYears']) {
  assert.match(apiSource, new RegExp(`${key}:`), `the question preview client must retain cloud ${key} choices`);
}
assert.match(source, /questionSourceLabel\((?:rawQuestion|question)\)/, 'question cards must consume the cloud source label or its structured fallback fields');
assert.doesNotMatch(source, /questionSearchText/, 'search and filters must never be applied only to loaded rows');
assert.match(source, /filterOptions\.subjects/, 'subject choices must come from the complete cloud filter contract');
assert.match(source, /'共 ' \+ questionTotal \+ ' 题'/, 'the summary must render the cloud filtered total rather than the loaded page length');
assert.match(apiSource, /nextCursor/, 'the question preview client must retain the cloud continuation cursor');
assert.match(source, /const QUESTION_PAGE_SIZE = \d+/, 'formal-role question browsing must use bounded cloud pages');
assert.match(source, /nextQuestionCursor/, 'the question page must retain the opaque continuation cursor');
assert.match(source, /questionBasketStore\.seedQuestions\(list\)/, 'incremental pages must extend rather than erase the shared basket question cache');
assert.match(source, /loadMoreQuestions/, 'formal-role native reach-bottom must request the next cloud page');
assert.match(source, /isVisitor[\s\S]*requestMoreQuestionAccess\(\)[\s\S]*loadMoreQuestions/, 'native reach-bottom must prompt visitors but silently load the next page for formal roles');
assert.match(source, /<QuestionBasketOverlay/, 'the question bank must mount the shared basket overlay');
assert.match(paperSource, /<QuestionBasketOverlay/, 'the paper editor must mount the same shared basket overlay');
assert.match(overlaySource, /questionBasketStore\.beginPaper\(selectedIds\)/, 'the basket must hand only the selected ordered subset to the paper editor');
assert.match(overlaySource, /pages\/question-paper\/index/, 'the shared basket must open the dedicated paper editor');
assert.match(paperSource, /questionBasketStore\.readPaperSelection\(\)/, 'the paper editor must read the account-scoped basket selection handoff');
assert.doesNotMatch(source, /createQuestionBasketRuntime/, 'the question page must not retain a private basket runtime');
assert.doesNotMatch(paperSource, /createQuestionBasketRuntime/, 'the paper page must not retain a second private basket runtime');
assert.match(paperSource, /miniappCloudBusinessApi\.createPaperExportTask/, 'Word and PDF tasks must use the limited cloud export route');
assert.match(paperSource, /miniappCloudBusinessApi\.requestPaperExportDelivery/, 'completed exports must request the NAS-backed delivery through cloud');
assert.match(paperSource, /miniappCloudBusinessApi\.downloadPaperExportDelivery/, 'downloads must use the scoped cloud delivery route');
assert.match(paperSource, /miniappCloudBusinessApi\.cancelPaperExportTask/, 'queued cloud exports must expose cancellation just as the desktop editor does');
assert.match(paperSource, /sectionTitle/, 'the paper editor must keep desktop-equivalent section grouping');
assert.match(paperSource, /sectionOptions/, 'the paper editor must offer the same reusable section choices as the desktop editor');
assert.match(paperSource, /typeStats/, 'the paper editor must expose the desktop-equivalent question-type summary');
assert.match(paperSource, /difficultyStats/, 'the paper editor must expose the desktop-equivalent difficulty summary');
assert.match(paperSource, /自定义分组/, 'the paper editor must make creating a custom section explicit instead of relying on an unlabeled field');
assert.match(paperSource, /score/, 'the paper editor must keep desktop-equivalent question scores');
assert.match(paperSource, /moveItem/, 'the paper editor must support question ordering');
assert.match(paperSource, /display\.options/, 'the paper editor must retain the selected question options through the shared display projection');
assert.match(paperSource, /answerPosition === 'after'/, 'the paper editor must render answers immediately after questions when that option is selected');
assert.match(paperSource, /参考答案与解析/, 'the paper editor must render the desktop-equivalent answer sheet when answers are placed at the end');
assert.match(paperSource, /knowledgeLabels/, 'the paper editor must retain the selected question knowledge labels');
assert.match(paperSource, /requestQuestionAssetDelivery/, 'the paper editor must fetch the same cloud-backed media as the question bank');
assert.match(paperSource, /<RichText/, 'the paper editor must render resolved question media');
assert.match(paperSource, /layout/, 'the edited layout must be submitted with the cloud export task');
for (const retired of ['authorityProjectionApi', 'createPaperTaskV2', 'getMiniappTaskResult', 'cancelMiniappTask', 'readQuestionPreview', 'hostBaseUrl', 'targetHostDeviceId']) {
  assert.ok(!source.includes(retired) && !paperSource.includes(retired), `question workflow must not retain the retired host-dependent ${retired}`);
}

console.log('miniapp question bank cloud delivery checks passed');
