'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { keepNumericUnitsTogether } = require('./questionTypography');
const source = '<p>−0.0100 μC，4.00 m/s，25 °C，6 N - 4 N = 2 N。</p><img src="/6 N.png" alt="6 N">';
const formatted = keepNumericUnitsTogether(source);
assert.match(formatted, /−0\.0100\u00a0μC/);
assert.match(formatted, /4\.00\u00a0m\/s/);
assert.match(formatted, /25\u00a0°C/);
assert.match(formatted, /6\u00a0N - 4\u00a0N = 2\u00a0N/);
assert.match(formatted, /src="\/6 N\.png" alt="6 N"/, 'HTML attributes and paths must remain byte-identical');
assert.equal(keepNumericUnitsTogether('<img src="/a > 6 N.png" alt="6 N">'), '<img src="/a > 6 N.png" alt="6 N">', 'a quoted greater-than must not expose attribute text to formatting');
assert.equal(keepNumericUnitsTogether('<p>6 Number; 5 sin(x); m = 3; 30°</p>'), '<p>6 Number; 5 sin(x); m = 3; 30°</p>');
assert.equal(keepNumericUnitsTogether(formatted), formatted, 'presentation must be idempotent');
const page = fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8');
assert.match(page, /keepNumericUnitsTogether\(resolveQuestionAssetRefs\(value, paths\)\)/, 'actual RichText projection must use the formatting boundary');
assert.match(page, /<QuestionBasketOverlay[\s\S]*?inline/, 'the question bank must expose an inline basket without covering cards');
const panel = page.slice(page.indexOf("className='question-filter-panel'"), page.indexOf("{previewState !== 'ready'"));
assert.match(panel, /<QuestionBasketOverlay/, 'the basket must remain accessible beside the filtering controls');
console.log('question typography precision, no-break spacing, safe attributes and inline basket checks passed');
(async () => {
  const sass = require('sass'), postcss = require('postcss'), pxtransform = require('postcss-pxtransform');
  const styles = fs.readFileSync(path.join(__dirname, 'index.scss'), 'utf8');
  const basket = fs.readFileSync(path.join(__dirname, '../../components/QuestionBasketOverlay.scss'), 'utf8');
  const result = await postcss([pxtransform({ platform: 'h5', designWidth: 375, deviceRatio: { 375: 2 } })]).process(sass.compileString(styles + '\n' + basket).css, { from: undefined });
  let narrowColumns, inlineHeight, inlinePosition;
  result.root.walkAtRules('media', media => { if (/max-width:\s*420px/i.test(media.params)) media.walkRules('.question-options.cols-4', rule => rule.walkDecls('grid-template-columns', d => { narrowColumns = d.value; })); });
  result.root.walkRules('.global-question-basket.inline-entry', rule => rule.walkDecls(d => { if (d.prop === 'min-height') inlineHeight = d.value; if (d.prop === 'position') inlinePosition = d.value; }));
  assert.equal(narrowColumns, 'repeat(2, minmax(0, 1fr))', 'the narrow 390px viewport must actually match after Taro CSS compilation');
  assert.equal(inlineHeight.toLowerCase(), '44px');
  assert.equal(inlinePosition, 'static');
  const declarations = {};
  result.root.walkRules(rule => rule.walkDecls(decl => { for (const selector of rule.selector.split(',').map(v => v.trim())) (declarations[selector] ||= {})[decl.prop] = decl.value; }));
  assert.equal(declarations['.question-basket-select-all']['white-space'], 'nowrap', 'checkbox label must never collapse into a vertical column');
  assert.equal(declarations['.question-basket-selection-bar']['flex-wrap'], 'wrap');
  assert.equal(declarations['.question-basket-head .question-basket-close']['width'], 'auto', 'the actual H5 class needs greater specificity than Taro full-width buttons');
  assert.equal(declarations['.question-basket-head .question-basket-close']['font-size'].toLowerCase(), '14px');
  assert.equal(declarations['.question-basket-footer']['flex-shrink'], '0');
  console.log('real Taro H5 typography/basket/narrow-column stylesheet checks passed');
})().catch(error => { console.error(error); process.exitCode = 1; });
