const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const file = __dirname + '/questionImageCleanup.ts';
const source = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : 'export const cleanHiddenQuestionImages = value => ({ value, removed: [] });';
const mod = { exports: {} };
new Function('module', 'exports', ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText)(mod, mod.exports);
const image = (width, height, alt = 'image.png', assetKey = 'image') => ({ type: 'image', attrs: { width, height, alt, assetKey } });
const doc = content => ({ type: 'doc', content });
const section = doc([image(1, 1), image(12, 6, '网站标识 www.example.com'), image(12, 6, '电路元件'), image(215, 98)]);
const value = { version: 1, type: 'question-document', sections: { stem: section, options: [{ id: 'o', content: section }], subQuestions: [{ id: 's', content: section, answer: section }], answer: section, analysis: section } };
const { value: cleaned, removed } = mod.exports.cleanHiddenQuestionImages(value);
assert.equal(removed.length, 12, 'all six content areas must be cleaned');
assert.equal(cleaned.sections.stem.content.length, 2);
assert.equal(value.sections.stem.content.length, 4, 'cleanup never mutates the draft or history');
const protectedDoc = { ...value, sections: { ...value.sections, stem: doc([{ type: 'formula', attrs: { previewRef: 'question-asset://preview' } }, image(1, 1, 'image', 'preview'), image(1, 1, 'MathType preview'), image(30, 10, 'website logo'), image(undefined, undefined, 'logo')]), options: [], subQuestions: [], answer: doc([]), analysis: doc([]) } };
assert.equal(mod.exports.cleanHiddenQuestionImages(protectedDoc).removed.length, 0, 'formula previews, visible images and unknown sizes are preserved');
assert.equal(mod.exports.cleanHiddenQuestionImages(cleaned).removed.length, 0, 'cleanup is idempotent');
const importPreview = { ...protectedDoc, sections: { ...protectedDoc.sections, stem: doc([{ type: 'paragraph', content: [{ type: 'formula', attrs: { id: 'preview-formula', previewRef: 'word/media/image1.png', canonicalLatex: '', displayMode: 'inline', conversionStatus: 'preview_only' } }] }, image(1, 1, 'image1.png', 'abc123')]) } };
assert.equal(mod.exports.cleanHiddenQuestionImages(importPreview).removed.length, 0, 'Word part paths protect their corresponding hashed image preview');
const table = { ...protectedDoc, sections: { ...protectedDoc.sections, stem: doc([{ type: 'table', content: [{ type: 'tableRow', content: [{ type: 'tableCell', content: [image(1, 1)] }] }] }]) } };
assert.deepEqual(mod.exports.cleanHiddenQuestionImages(table).value.sections.stem.content[0].content[0].content[0].content, [{ type: 'paragraph' }], 'an emptied table cell remains valid and editable');
console.log('hidden image cleanup across all question sections passed');
